# Generated by Django 4.2 on 2025-12-15 19:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("training", "0004_trainingcheckpoint_alter_trainingsession_options_and_more"),
        ("organizations", "0004_organization_is_vendor"),
    ]

    operations = [
        migrations.CreateModel(
            name="ComputeFallback",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "priority",
                    models.PositiveIntegerField(
                        help_text="Lower number = higher priority (1, 2, 3...)"
                    ),
                ),
            ],
            options={
                "db_table": "compute_fallback",
                "ordering": ["priority"],
            },
        ),
        migrations.CreateModel(
            name="ComputeProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("profile_id", models.CharField(max_length=255, unique=True)),
                ("name", models.CharField(max_length=255)),
                (
                    "user_credentials",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Encrypted user credentials for cloud providers",
                    ),
                ),
                (
                    "default_instance_type",
                    models.CharField(
                        help_text="Default instance type (e.g., ml.p3.2xlarge, n1-highmem-8)",
                        max_length=100,
                    ),
                ),
                (
                    "max_concurrent_jobs",
                    models.PositiveIntegerField(
                        default=5, help_text="Max concurrent training jobs"
                    ),
                ),
                (
                    "strategy",
                    models.CharField(
                        choices=[
                            ("cheapest", "Cheapest Available"),
                            ("fastest", "Fastest (Best GPU)"),
                            ("preferred", "Preferred Provider"),
                            ("queue", "Queue on Platform GPUs"),
                        ],
                        default="queue",
                        max_length=20,
                    ),
                ),
                (
                    "max_cost_per_hour",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Max cost per hour in USD",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "max_training_hours",
                    models.PositiveIntegerField(
                        default=24, help_text="Max hours per training job"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "is_default",
                    models.BooleanField(
                        default=False, help_text="Default profile for this organization"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Compute Profiles",
                "db_table": "compute_profile",
            },
        ),
        migrations.CreateModel(
            name="ComputeProvider",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                (
                    "provider_type",
                    models.CharField(
                        choices=[
                            ("platform-gpu", "Platform GPU Workers"),
                            ("platform-cpu", "Platform CPU Workers"),
                            ("aws-sagemaker", "AWS SageMaker"),
                            ("gcp-vertex", "GCP Vertex AI"),
                            ("azure-ml", "Azure ML"),
                            ("kubernetes", "Kubernetes Cluster"),
                            ("modal", "Modal Labs"),
                            ("runpod", "RunPod"),
                        ],
                        max_length=50,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                (
                    "system_config",
                    models.JSONField(
                        default=dict,
                        help_text="Provider credentials and global settings (admin only)",
                    ),
                ),
                (
                    "available_instances",
                    models.JSONField(
                        default=list,
                        help_text="List of available instance types with specs",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "requires_user_credentials",
                    models.BooleanField(
                        default=False,
                        help_text="Whether users need to provide their own credentials",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name_plural": "Compute Providers",
                "db_table": "compute_provider",
            },
        ),
        migrations.CreateModel(
            name="TrainingJob",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("job_id", models.CharField(max_length=255, unique=True)),
                ("instance_type", models.CharField(max_length=100)),
                (
                    "external_job_id",
                    models.CharField(
                        blank=True,
                        help_text="Job ID in external system (SageMaker ARN, Vertex AI job name, etc.)",
                        max_length=500,
                    ),
                ),
                (
                    "estimated_cost",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=10, null=True
                    ),
                ),
                (
                    "actual_cost",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=10, null=True
                    ),
                ),
                (
                    "gpu_hours",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "actual_provider",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="executed_jobs",
                        to="compute.computeprovider",
                    ),
                ),
                (
                    "compute_profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="training_jobs",
                        to="compute.computeprofile",
                    ),
                ),
                (
                    "training_session",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="training_job",
                        to="training.trainingsession",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Training Jobs",
                "db_table": "training_job",
            },
        ),
        migrations.AddField(
            model_name="computeprofile",
            name="fallback_providers",
            field=models.ManyToManyField(
                blank=True,
                related_name="fallback_for_profiles",
                through="compute.ComputeFallback",
                to="compute.computeprovider",
            ),
        ),
        migrations.AddField(
            model_name="computeprofile",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="compute_profiles",
                to="organizations.organization",
            ),
        ),
        migrations.AddField(
            model_name="computeprofile",
            name="provider",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="compute_profiles",
                to="compute.computeprovider",
            ),
        ),
        migrations.AddField(
            model_name="computefallback",
            name="profile",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="compute.computeprofile"
            ),
        ),
        migrations.AddField(
            model_name="computefallback",
            name="provider",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="compute.computeprovider",
            ),
        ),
        migrations.AddIndex(
            model_name="computeprofile",
            index=models.Index(
                fields=["organization", "is_default"],
                name="compute_pro_organiz_67435e_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="computeprofile",
            unique_together={("organization", "name")},
        ),
        migrations.AlterUniqueTogether(
            name="computefallback",
            unique_together={("profile", "priority")},
        ),
    ]
