# Generated by Django 4.2 on 2025-12-29 11:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0004_organization_is_vendor"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("compute", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Agent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "agent_id",
                    models.CharField(
                        help_text="Unique identifier for this agent",
                        max_length=255,
                        unique=True,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Human-readable name for this agent", max_length=255
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("ready", "Ready"),
                            ("busy", "Busy"),
                            ("offline", "Offline"),
                            ("error", "Error"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "gpu_info",
                    models.JSONField(
                        default=list, help_text="List of GPUs available on this agent"
                    ),
                ),
                (
                    "system_info",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="System specs (CPU, RAM, OS, etc.)",
                    ),
                ),
                (
                    "last_heartbeat",
                    models.DateTimeField(
                        blank=True,
                        help_text="Last time agent sent heartbeat",
                        null=True,
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, help_text="Agent IP address", null=True
                    ),
                ),
                (
                    "version",
                    models.CharField(
                        blank=True, help_text="Agent software version", max_length=50
                    ),
                ),
                (
                    "max_concurrent_jobs",
                    models.PositiveIntegerField(
                        default=1, help_text="Maximum concurrent training jobs"
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True, help_text="Admin notes about this agent"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_agents",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        help_text="Organization that owns this agent",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="agents",
                        to="organizations.organization",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Agents",
                "db_table": "agent",
            },
        ),
        migrations.AlterField(
            model_name="computeprovider",
            name="provider_type",
            field=models.CharField(
                choices=[
                    ("platform-gpu", "Platform GPU Workers"),
                    ("platform-cpu", "Platform CPU Workers"),
                    ("on-premise-agent", "On-Premise Agent"),
                    ("aws-sagemaker", "AWS SageMaker"),
                    ("gcp-vertex", "GCP Vertex AI"),
                    ("azure-ml", "Azure ML"),
                    ("kubernetes", "Kubernetes Cluster"),
                    ("modal", "Modal Labs"),
                    ("runpod", "RunPod"),
                ],
                max_length=50,
            ),
        ),
        migrations.CreateModel(
            name="AgentAPIKey",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "key_id",
                    models.CharField(
                        help_text="Public key identifier (e.g., org_123_agent_abc)",
                        max_length=255,
                        unique=True,
                    ),
                ),
                (
                    "key_hash",
                    models.CharField(help_text="Hashed secret key", max_length=255),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Human-readable name for this key", max_length=255
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "last_used",
                    models.DateTimeField(
                        blank=True, help_text="Last time this key was used", null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "expires_at",
                    models.DateTimeField(
                        blank=True, help_text="Optional expiration date", null=True
                    ),
                ),
                (
                    "agent",
                    models.ForeignKey(
                        blank=True,
                        help_text="Agent this key is for (null if not yet assigned)",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="api_keys",
                        to="compute.agent",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="agent_api_keys",
                        to="organizations.organization",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Agent API Keys",
                "db_table": "agent_api_key",
            },
        ),
        migrations.AddIndex(
            model_name="agentapikey",
            index=models.Index(
                fields=["organization", "is_active"],
                name="agent_api_k_organiz_d39731_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="agent",
            index=models.Index(
                fields=["organization", "status"], name="agent_organiz_4cd2b3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="agent",
            index=models.Index(
                fields=["last_heartbeat"], name="agent_last_he_ad84a0_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="agent",
            unique_together={("organization", "name")},
        ),
    ]
