# Generated by Django 4.2 on 2026-04-25 07:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0004_organization_is_vendor'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ml_models', '0008_modelversion_tags'),
        ('projects', '0026_projectimage_last_review_version_and_more'),
        ('compute', '0002_agent_alter_computeprovider_provider_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InferenceJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_id', models.CharField(max_length=255, unique=True)),
                ('image_ids', models.JSONField(default=list)),
                ('confidence_threshold', models.FloatField(default=0.25)),
                ('onnx_presigned_url', models.TextField(blank=True)),
                ('onnx_url_expires_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], db_index=True, default='pending', max_length=20)),
                ('result_summary', models.JSONField(blank=True, default=dict, help_text='Counts of annotations created per class after completion')),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inference_jobs', to='compute.agent')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('model_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inference_jobs', to='ml_models.modelversion')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inference_jobs', to='organizations.organization')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inference_jobs', to='projects.project')),
            ],
            options={
                'verbose_name_plural': 'Inference Jobs',
                'db_table': 'inference_job',
            },
        ),
        migrations.AddIndex(
            model_name='inferencejob',
            index=models.Index(fields=['organization', 'status'], name='inference_j_organiz_ad5a54_idx'),
        ),
    ]
