# Generated by Django 4.2 on 2024-11-20 16:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0002_edgebox'),
        ('images', '0003_remove_image_edge_box_image_source_of_origin'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='edge_box',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tenants.edgebox'),
        ),
    ]
