# Generated by Django 4.2 on 2025-10-23 16:08

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0003_alter_organization_options_organization_created_by_and_more'),
        ('images', '0007_image_height_image_width'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='image',
            options={'verbose_name': 'Image', 'verbose_name_plural': 'Images'},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'verbose_name': 'Tag', 'verbose_name_plural': 'Tags'},
        ),
        migrations.AddField(
            model_name='image',
            name='checksum',
            field=models.CharField(blank=True, help_text='SHA-256 checksum of file', max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='image',
            name='file_format',
            field=models.CharField(default='jpg', help_text='Image format (jpg, png, tiff, etc.)', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='image',
            name='file_size',
            field=models.BigIntegerField(default=1000, help_text='File size in bytes', validators=[django.core.validators.MinValueValidator(0)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='image',
            name='name',
            field=models.CharField(default='fake', help_text='Human-readable image name', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='image',
            name='organization',
            field=models.ForeignKey(default=1, help_text='Organization that owns this image', on_delete=django.db.models.deletion.CASCADE, related_name='images', to='organizations.organization'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='image',
            name='original_filename',
            field=models.CharField(default='default', help_text='Original filename when uploaded', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='image',
            name='storage_key',
            field=models.CharField(default=1, help_text='Full path/key in storage (e.g., org-123/images/2025/img.jpg)', max_length=500),
            preserve_default=False,
        ),
    ]
