# Generated by Django 4.2 on 2025-10-23 16:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0003_alter_organization_options_organization_created_by_and_more'),
        ('images', '0008_alter_image_options_alter_tag_options_image_checksum_and_more'),
        ('storage', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='storage_profile',
            field=models.ForeignKey(default=1, help_text='Storage profile where this image is stored', on_delete=django.db.models.deletion.PROTECT, related_name='images', to='storage.storageprofile'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='image',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='image',
            name='uploaded_by',
            field=models.ForeignKey(blank=True, help_text='User who uploaded this image', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_images', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tag',
            name='color',
            field=models.CharField(default='#3B82F6', help_text='Hex color for UI display', max_length=7),
        ),
        migrations.AddField(
            model_name='tag',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tag',
            name='description',
            field=models.TextField(blank=True, help_text='Tag description'),
        ),
        migrations.AddField(
            model_name='tag',
            name='organization',
            field=models.ForeignKey(default=1, help_text='Organization that owns this tag', on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='organizations.organization'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='image',
            name='height',
            field=models.PositiveIntegerField(blank=True, default=1000, help_text='Image height in pixels'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='image',
            name='meta_info',
            field=models.JSONField(blank=True, default=dict, help_text='Additional metadata (EXIF, GPS, camera info, etc.)', null=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='source_of_origin',
            field=models.CharField(blank=True, help_text='Source where image came from (camera, upload, API, etc.)', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='width',
            field=models.PositiveIntegerField(blank=True, default=1000, help_text='Image width in pixels'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(help_text='Tag name', max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='image',
            unique_together={('organization', 'storage_key')},
        ),
        migrations.AlterUniqueTogether(
            name='tag',
            unique_together={('organization', 'name')},
        ),
        migrations.AddIndex(
            model_name='image',
            index=models.Index(fields=['organization', 'created_at'], name='image_organiz_0425f6_idx'),
        ),
        migrations.AddIndex(
            model_name='image',
            index=models.Index(fields=['storage_profile', 'storage_key'], name='image_storage_de68b0_idx'),
        ),
        migrations.AddIndex(
            model_name='image',
            index=models.Index(fields=['uploaded_by', 'created_at'], name='image_uploade_ba2a1e_idx'),
        ),
        migrations.AddIndex(
            model_name='tag',
            index=models.Index(fields=['organization', 'name'], name='tag_organiz_ab0480_idx'),
        ),
        migrations.RemoveField(
            model_name='image',
            name='annotated',
        ),
        migrations.RemoveField(
            model_name='image',
            name='processed',
        ),
        migrations.RemoveField(
            model_name='image',
            name='sensorbox',
        ),
    ]
