# Generated by Django 4.2 on 2025-10-31 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0009_image_storage_profile_image_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image_name',
            field=models.CharField(max_length=255),
        ),
    ]
