# Generated by Django 4.2 on 2026-02-14 12:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('organizations', '0004_organization_is_vendor'),
    ]

    operations = [
        migrations.CreateModel(
            name='APIKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(db_index=True, max_length=255, unique=True)),
                ('prefix', models.CharField(db_index=True, max_length=16)),
                ('hashed_key', models.CharField(max_length=128)),
                ('name', models.CharField(help_text='Friendly name for this key', max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('scope', models.CharField(choices=[('organization', 'Organization-wide'), ('user', 'User-specific')], default='organization', help_text='Organization-wide or user-specific', max_length=20)),
                ('permission', models.CharField(choices=[('read', 'Read-only'), ('write', 'Read & Write'), ('admin', 'Admin (Full Access)')], default='read', help_text='Permission level: read, write, or admin', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('usage_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(help_text='Key expiration date (default: 90 days from creation)')),
                ('rate_limit_per_minute', models.IntegerField(default=60, help_text='Max requests per minute (0 = unlimited)')),
                ('rate_limit_per_hour', models.IntegerField(default=1000, help_text='Max requests per hour (0 = unlimited)')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_api_keys', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_keys', to='organizations.organization')),
                ('user', models.ForeignKey(blank=True, help_text='If user-specific, which user this key belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='api_keys', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'API Key',
                'verbose_name_plural': 'API Keys',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='APIKeyUsageLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('endpoint', models.CharField(max_length=255)),
                ('method', models.CharField(max_length=10)),
                ('status_code', models.IntegerField()),
                ('response_time_ms', models.IntegerField(null=True)),
                ('ip_address', models.GenericIPAddressField(null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('api_key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage_logs', to='api_keys.apikey')),
            ],
            options={
                'verbose_name': 'API Key Usage Log',
                'verbose_name_plural': 'API Key Usage Logs',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='APIKeyRateLimit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('window_start', models.DateTimeField(db_index=True)),
                ('window_type', models.CharField(choices=[('minute', 'Per Minute'), ('hour', 'Per Hour')], max_length=10)),
                ('request_count', models.IntegerField(default=0)),
                ('api_key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rate_limits', to='api_keys.apikey')),
            ],
            options={
                'verbose_name': 'API Key Rate Limit',
                'verbose_name_plural': 'API Key Rate Limits',
            },
        ),
        migrations.AddIndex(
            model_name='apikeyusagelog',
            index=models.Index(fields=['api_key', 'timestamp'], name='api_keys_ap_api_key_61c98b_idx'),
        ),
        migrations.AddIndex(
            model_name='apikeyusagelog',
            index=models.Index(fields=['timestamp'], name='api_keys_ap_timesta_337266_idx'),
        ),
        migrations.AddIndex(
            model_name='apikeyratelimit',
            index=models.Index(fields=['api_key', 'window_type', 'window_start'], name='api_keys_ap_api_key_d982be_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='apikeyratelimit',
            unique_together={('api_key', 'window_start', 'window_type')},
        ),
        migrations.AddIndex(
            model_name='apikey',
            index=models.Index(fields=['key'], name='api_keys_ap_key_d2e2bb_idx'),
        ),
        migrations.AddIndex(
            model_name='apikey',
            index=models.Index(fields=['prefix'], name='api_keys_ap_prefix_fda2a7_idx'),
        ),
        migrations.AddIndex(
            model_name='apikey',
            index=models.Index(fields=['organization', 'is_active'], name='api_keys_ap_organiz_cd2068_idx'),
        ),
        migrations.AddIndex(
            model_name='apikey',
            index=models.Index(fields=['hashed_key'], name='api_keys_ap_hashed__07623c_idx'),
        ),
    ]
