# Generated by Django 4.2 on 2026-03-29 19:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api_keys', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='apikey',
            name='api_keys_ap_key_d2e2bb_idx',
        ),
        migrations.RemoveIndex(
            model_name='apikey',
            name='api_keys_ap_prefix_fda2a7_idx',
        ),
        migrations.RenameField(
            model_name='apikey',
            old_name='prefix',
            new_name='key_prefix',
        ),
        migrations.RenameField(
            model_name='apikey',
            old_name='permission',
            new_name='permissions',
        ),
        migrations.RemoveField(
            model_name='apikey',
            name='key',
        ),
        migrations.RemoveField(
            model_name='apikey',
            name='user',
        ),
        migrations.AddField(
            model_name='apikey',
            name='allowed_ips',
            field=models.JSONField(blank=True, default=list, help_text='List of allowed IP addresses/CIDRs (empty = allow all)'),
        ),
        migrations.AddField(
            model_name='apikey',
            name='api_key_id',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AddField(
            model_name='apikey',
            name='owned_by',
            field=models.ForeignKey(blank=True, help_text='User this key acts on behalf of (null = acts as creator)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='api_keys', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='apikey',
            name='rotated_from',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rotated_to', to='api_keys.apikey'),
        ),
        migrations.AddField(
            model_name='apikey',
            name='scopes',
            field=models.JSONField(blank=True, default=list, help_text='List of allowed scopes (e.g. ["projects:read", "images:*"]). Empty = all.'),
        ),
        migrations.AddField(
            model_name='apikey',
            name='version',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='apikey',
            name='hashed_key',
            field=models.CharField(db_index=True, max_length=128),
        ),
        migrations.AddIndex(
            model_name='apikey',
            index=models.Index(fields=['key_prefix'], name='api_keys_ap_key_pre_4994e1_idx'),
        ),
        migrations.AddIndex(
            model_name='apikey',
            index=models.Index(fields=['api_key_id'], name='api_keys_ap_api_key_9e812d_idx'),
        ),
    ]
