# Generated by Django 4.2 on 2025-11-15 22:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('provider', models.CharField(choices=[('microsoft', 'Microsoft'), ('google', 'Google')], max_length=20)),
                ('provider_user_id', models.CharField(help_text='User ID from the OAuth provider', max_length=255)),
                ('subject', models.CharField(help_text="Stable subject/identifier from the provider (e.g. 'sub' claim).", max_length=255)),
                ('issuer', models.CharField(blank=True, help_text='OIDC issuer URI / authority (e.g. https://login.microsoftonline.com/{tenant}/v2.0).', max_length=255)),
                ('tenant_id', models.CharField(blank=True, help_text='Provider tenant identifier (e.g. Azure AD tenant ID).', max_length=128)),
                ('email', models.EmailField(help_text='Email from OAuth provider', max_length=254)),
                ('email_verified', models.BooleanField(default=False, help_text='Whether the provider marked this email as verified.')),
                ('display_name', models.CharField(blank=True, help_text='Full display name from the provider profile.', max_length=255)),
                ('given_name', models.CharField(blank=True, max_length=150)),
                ('family_name', models.CharField(blank=True, max_length=150)),
                ('avatar_url', models.URLField(blank=True, help_text='Profile picture URL if provided.', max_length=500)),
                ('is_primary', models.BooleanField(default=False, help_text='Whether this is the primary external account for this provider.')),
                ('is_revoked', models.BooleanField(default=False, help_text='Set to True if user revoked / unlinked this external account.')),
                ('access_token', models.TextField(blank=True, null=True)),
                ('refresh_token', models.TextField(blank=True, null=True)),
                ('token_expires_at', models.DateTimeField(blank=True, null=True)),
                ('extra_data', models.JSONField(blank=True, default=dict, help_text='Additional data from provider (name, avatar, etc.)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_login', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_accounts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'social_accounts',
            },
        ),
        migrations.AddIndex(
            model_name='socialaccount',
            index=models.Index(fields=['user', 'provider'], name='social_acco_user_id_e2981d_idx'),
        ),
        migrations.AddIndex(
            model_name='socialaccount',
            index=models.Index(fields=['provider', 'email'], name='social_acco_provide_895a7a_idx'),
        ),
        migrations.AddIndex(
            model_name='socialaccount',
            index=models.Index(fields=['provider', 'subject'], name='idx_extacc_provider_subject'),
        ),
        migrations.AlterUniqueTogether(
            name='socialaccount',
            unique_together={('provider', 'provider_user_id')},
        ),
    ]
