# Generated by Django 4.2 on 2024-08-05 14:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='meta_info',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Annotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annotation_file', models.FileField(upload_to='labels/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('meta_info', models.JSONField(blank=True, null=True)),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.image')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.project')),
            ],
            options={
                'verbose_name_plural': 'Annotations',
                'db_table': 'annotation',
            },
        ),
    ]
