# Generated by Django 4.2 on 2024-11-17 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0003_image_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='mode',
        ),
        migrations.RemoveField(
            model_name='project',
            name='project_type',
        ),
        migrations.DeleteModel(
            name='Annotation',
        ),
        migrations.DeleteModel(
            name='Image',
        ),
        migrations.DeleteModel(
            name='ImageMode',
        ),
        migrations.DeleteModel(
            name='Project',
        ),
        migrations.DeleteModel(
            name='ProjectType',
        ),
    ]
