# Generated by Django 4.2 on 2024-11-17 12:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EdgeBox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edge_box_id', models.CharField(max_length=255, unique=True)),
                ('edge_box_location', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('plant', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='tenants.plant')),
            ],
            options={
                'verbose_name_plural': 'Edge Boxes',
                'db_table': 'edge_box',
            },
        ),
    ]
