# Generated by Django 4.2 on 2025-04-13 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='image_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
