# Generated by Django 4.2 on 2025-04-22 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_alter_job_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='batch_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
