# Generated by Django 4.2 on 2024-12-18 09:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0003_remove_projectimage_annotations'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnnotationType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Annotation Types',
                'db_table': 'annotation_type',
            },
        ),
        migrations.CreateModel(
            name='AnnotationGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='annotation_groups', to='projects.project')),
            ],
            options={
                'verbose_name_plural': 'Annotation Groups',
                'db_table': 'annotation_group',
            },
        ),
        migrations.CreateModel(
            name='AnnotationClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_id', models.PositiveIntegerField()),
                ('name', models.CharField(max_length=255)),
                ('color', models.CharField(blank=True, max_length=7, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('annotation_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='annotations.annotationgroup')),
            ],
            options={
                'verbose_name_plural': 'Annotation Classes',
                'db_table': 'annotation_class',
                'unique_together': {('annotation_group', 'class_id')},
            },
        ),
        migrations.CreateModel(
            name='Annotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(blank=True, max_length=255, null=True)),
                ('annotation_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='annotations', to='annotations.annotationclass')),
                ('annotation_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='annotations', to='annotations.annotationtype')),
                ('project_image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='annotations', to='projects.projectimage')),
            ],
            options={
                'verbose_name_plural': 'Annotations',
                'db_table': 'annotation',
            },
        ),
    ]
