# Generated by Django 4.2 on 2025-01-06 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='annotation',
            name='reviewed',
            field=models.BooleanField(default=False),
        ),
    ]
