# Generated by Django 4.2 on 2025-01-06 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotations', '0002_annotation_reviewed'),
    ]

    operations = [
        migrations.AddField(
            model_name='annotation',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
