# Generated by Django 4.2 on 2025-01-20 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotations', '0003_annotation_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='annotation',
            name='annotation_uid',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
    ]
