# Generated by Django 4.2 on 2025-01-21 12:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('annotations', '0004_annotation_annotation_uid'),
    ]

    operations = [
        migrations.AddField(
            model_name='annotation',
            name='rating',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='annotations.annotationclass'),
        ),
    ]
