# Generated by Django 4.2 on 2025-03-11 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotations', '0005_annotation_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='annotation',
            name='feedback_provided',
            field=models.BooleanField(default=False),
        ),
    ]
