# Generated by Django 4.2 on 2025-05-22 05:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('annotations', '0007_annotation_annotation_source'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnnotationAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evaluation_status', models.CharField(blank=True, choices=[('TP', 'True Positive'), ('FP', 'False Positive'), ('FN', 'False Negative')], max_length=2, null=True)),
                ('was_edited', models.BooleanField(default=False)),
                ('iou', models.FloatField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(auto_now=True)),
                ('reviewed_by', models.CharField(blank=True, max_length=255, null=True)),
                ('annotation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='audit', to='annotations.annotation')),
                ('matched_manual_annotation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matched_predictions', to='annotations.annotation')),
            ],
            options={
                'verbose_name_plural': 'Annotation Audits',
                'db_table': 'annotation_audit',
            },
        ),
    ]
