# Generated by Django 4.2 on 2025-06-12 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotations', '0008_annotationaudit'),
    ]

    operations = [
        migrations.AddField(
            model_name='annotation',
            name='confidence',
            field=models.FloatField(blank=True, help_text="Prediction confidence (only applicable if source is 'prediction')", null=True),
        ),
    ]
