# Generated by Django 4.2 on 2025-11-08 20:42

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('annotations', '0009_annotation_confidence'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='annotation',
            name='feedback_provided',
        ),
        migrations.RemoveField(
            model_name='annotation',
            name='rating',
        ),
        migrations.AddField(
            model_name='annotation',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, help_text='When annotations were reviewed', null=True),
        ),
        migrations.AddField(
            model_name='annotation',
            name='reviewed_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='annotations_reviewed', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='annotation',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='annotation',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='annotations_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='annotation',
            name='version',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='annotation',
            name='annotation_source',
            field=models.CharField(choices=[('manual', 'Manual Annotation'), ('prediction', 'Model Prediction')], db_index=True, default='manual', max_length=20),
        ),
        migrations.AlterField(
            model_name='annotation',
            name='confidence',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='annotation',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='annotations_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='annotation',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AddIndex(
            model_name='annotation',
            index=models.Index(fields=['project_image', 'is_active'], name='annotation_project_ab903f_idx'),
        ),
        migrations.AddIndex(
            model_name='annotation',
            index=models.Index(fields=['annotation_source', 'is_active'], name='annotation_annotat_f479c9_idx'),
        ),
        migrations.AddIndex(
            model_name='annotation',
            index=models.Index(fields=['annotation_class', 'is_active'], name='annotation_annotat_428a5d_idx'),
        ),
        migrations.AddIndex(
            model_name='annotation',
            index=models.Index(fields=['created_at'], name='annotation_created_f118bb_idx'),
        ),
        migrations.AddIndex(
            model_name='annotation',
            index=models.Index(fields=['annotation_uid'], name='annotation_annotat_c99eb7_idx'),
        ),
    ]
