# Generated by Django 4.2 on 2025-11-09 00:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('annotations', '0012_alter_annotation_created_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='annotation',
            name='edit_magnitude',
            field=models.FloatField(blank=True, help_text='Magnitude of edit (0=no change, 1=total change)', null=True),
        ),
        migrations.AddField(
            model_name='annotation',
            name='edit_type',
            field=models.CharField(choices=[('none', 'No Edit'), ('minor', 'Minor Adjustment'), ('major', 'Major Change'), ('class_change', 'Class Changed'), ('deleted', 'Deleted')], default='none', help_text='Type of edit made', max_length=20),
        ),
        migrations.AddField(
            model_name='annotationaudit',
            name='edit_magnitude',
            field=models.FloatField(blank=True, help_text='How much bbox changed (0-1)', null=True),
        ),
        migrations.AddField(
            model_name='annotationaudit',
            name='edit_type',
            field=models.CharField(blank=True, help_text='Type of edit: none, minor, major, class_change, deleted', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='annotationaudit',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audits_reviewed', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='annotationaudit',
            index=models.Index(fields=['evaluation_status'], name='annotation__evaluat_3b48db_idx'),
        ),
        migrations.AddIndex(
            model_name='annotationaudit',
            index=models.Index(fields=['edit_type'], name='annotation__edit_ty_7eef40_idx'),
        ),
    ]
