# Generated by Django 4.2 on 2025-11-09 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotations', '0013_annotation_edit_magnitude_annotation_edit_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annotation',
            name='edit_type',
            field=models.CharField(blank=True, choices=[('none', 'No Edit'), ('minor', 'Minor Adjustment'), ('major', 'Major Change'), ('class_change', 'Class Changed'), ('deleted', 'Deleted')], default='none', help_text='Type of edit made', max_length=20, null=True),
        ),
    ]
