# Generated by Django 4.2 on 2025-11-23 18:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0026_projectimage_last_review_version_and_more'),
        ('annotations', '0014_alter_annotation_edit_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='SuggestionSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suggestion_id', models.UUIDField(default=uuid.uuid4)),
                ('source_type', models.CharField(choices=[('sam_auto', 'SAM Auto-Segment'), ('sam_point', 'SAM Point Prompt'), ('similar', 'Similar Object'), ('prev_frame', 'Previous Frame'), ('label', 'Label Suggestion')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('suggestions_generated', models.IntegerField(default=0)),
                ('suggestions_accepted', models.IntegerField(default=0)),
                ('suggestions_rejected', models.IntegerField(default=0)),
                ('source_annotation_uid', models.CharField(blank=True, max_length=100, null=True)),
                ('source_image_id', models.IntegerField(blank=True, null=True)),
                ('model_version', models.CharField(blank=True, max_length=50, null=True)),
                ('meta_info', models.JSONField(blank=True, default=dict, null=True)),
                ('model_name', models.CharField(default='sam_v2', help_text='SAM model version (sam_v1, sam_v2, sam_v3)', max_length=20)),
                ('model_device', models.CharField(default='cuda', help_text='Device (cuda or cpu)', max_length=10)),
                ('model_precision', models.CharField(default='fp16', help_text='Precision (fp16 or fp32)', max_length=10)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('project_image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suggestion_sessions', to='projects.projectimage')),
            ],
            options={
                'db_table': 'suggestion_session',
            },
        ),
        migrations.AddIndex(
            model_name='suggestionsession',
            index=models.Index(fields=['project_image', 'created_at'], name='suggestion__project_1e90db_idx'),
        ),
        migrations.AddIndex(
            model_name='suggestionsession',
            index=models.Index(fields=['source_type', 'created_at'], name='suggestion__source__42f72d_idx'),
        ),
    ]
