# Generated by Django 4.2 on 2026-01-23 15:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('annotations', '0015_suggestionsession_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='annotationaudit',
            name='iou',
        ),
        migrations.AddField(
            model_name='annotation',
            name='model_version',
            field=models.CharField(blank=True, db_index=True, help_text="e.g. 'yolov8-large-v2.1'", max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='annotation',
            name='original_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='original_predictions', to='annotations.annotationclass'),
        ),
        migrations.AddField(
            model_name='annotation',
            name='original_data',
            field=models.JSONField(blank=True, help_text='Original bbox before any edits [x1,y1,x2,y2]', null=True),
        ),
        migrations.AddField(
            model_name='annotationaudit',
            name='localization_iou',
            field=models.FloatField(blank=True, help_text='IoU between original_data and current data (for edited TPs)', null=True),
        ),
        migrations.AddField(
            model_name='annotationaudit',
            name='original_confidence',
            field=models.FloatField(blank=True, help_text='Model confidence before any changes', null=True),
        ),
    ]
