# Generated by Django 4.2 on 2026-01-23 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotations', '0016_remove_annotationaudit_iou_annotation_model_version_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='annotation',
            name='annotation_project_ab903f_idx',
        ),
        migrations.RemoveIndex(
            model_name='annotation',
            name='annotation_annotat_f479c9_idx',
        ),
        migrations.RemoveIndex(
            model_name='annotation',
            name='annotation_annotat_428a5d_idx',
        ),
        migrations.RemoveField(
            model_name='annotation',
            name='is_active',
        ),
        migrations.AddIndex(
            model_name='annotation',
            index=models.Index(fields=['project_image', 'is_deleted'], name='annotation_project_fd6606_idx'),
        ),
        migrations.AddIndex(
            model_name='annotation',
            index=models.Index(fields=['annotation_source', 'is_deleted'], name='annotation_annotat_4e5865_idx'),
        ),
        migrations.AddIndex(
            model_name='annotation',
            index=models.Index(fields=['annotation_class', 'is_deleted'], name='annotation_annotat_0a6f78_idx'),
        ),
    ]
