# Generated by Django 4.2 on 2026-01-23 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotations', '0017_remove_annotation_annotation_project_ab903f_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='annotation',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AddIndex(
            model_name='annotation',
            index=models.Index(fields=['project_image', 'is_active'], name='annotation_project_ab903f_idx'),
        ),
        migrations.AddIndex(
            model_name='annotation',
            index=models.Index(fields=['annotation_source', 'is_active'], name='annotation_annotat_f479c9_idx'),
        ),
        migrations.AddIndex(
            model_name='annotation',
            index=models.Index(fields=['annotation_class', 'is_active'], name='annotation_annotat_428a5d_idx'),
        ),
    ]
