# Generated by Django 4.2 on 2026-01-23 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotations', '0018_annotation_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='annotationaudit',
            name='iou',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
