# Generated by Django 4.2 on 2025-05-11 13:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ml_models', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelversion',
            name='checkpoint',
            field=models.FileField(blank=True, max_length=1024, null=True, upload_to='ml_models/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pt', 'pth', 'h5', 'onnx'])]),
        ),
    ]
