# Generated by Django 4.2 on 2025-05-11 14:46

import django.core.validators
from django.db import migrations, models
import ml_models.models


class Migration(migrations.Migration):

    dependencies = [
        ('ml_models', '0003_model_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelversion',
            name='logs',
            field=models.FileField(blank=True, null=True, upload_to=ml_models.models.get_model_artifact_path),
        ),
        migrations.AlterField(
            model_name='modelversion',
            name='checkpoint',
            field=models.FileField(blank=True, max_length=1024, null=True, upload_to=ml_models.models.get_model_artifact_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pt', 'pth', 'h5', 'onnx'])]),
        ),
    ]
