# Generated by Django 4.2 on 2025-05-11 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ml_models', '0004_modelversion_logs_alter_modelversion_checkpoint'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Model Tags',
                'db_table': 'model_tag',
            },
        ),
        migrations.AddField(
            model_name='model',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='models', to='ml_models.modeltag'),
        ),
    ]
