# Generated by Django 4.2 on 2025-11-30 18:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0004_organization_is_vendor"),
        ("storage", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("projects", "0026_projectimage_last_review_version_and_more"),
        ("ml_models", "0005_modeltag_model_tags"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="modelversion",
            options={
                "ordering": ["-version_number"],
                "verbose_name_plural": "Model Versions",
            },
        ),
        migrations.AlterUniqueTogether(
            name="modelversion",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="model",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="model",
            name="deleted_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="deleted_models",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="model",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="model",
            name="model_id",
            field=models.CharField(
                default=django.utils.timezone.now,
                help_text="Unique identifier for this model",
                max_length=255,
                unique=True,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="model",
            name="organization",
            field=models.ForeignKey(
                default=1,
                help_text="Organization that owns this model",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ml_models",
                to="organizations.organization",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="modeltag",
            name="color",
            field=models.CharField(
                default="#3B82F6", help_text="Hex color for UI display", max_length=7
            ),
        ),
        migrations.AddField(
            model_name="modeltag",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="modeltag",
            name="organization",
            field=models.ForeignKey(
                default=1,
                help_text="Organization that owns this tag",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="model_tags",
                to="organizations.organization",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="modelversion",
            name="checkpoint_key",
            field=models.CharField(
                blank=True,
                help_text="Storage key for model checkpoint (e.g., org-123/models/model-1/v1/checkpoint.pt)",
                max_length=500,
            ),
        ),
        migrations.AddField(
            model_name="modelversion",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="modelversion",
            name="deployed_at",
            field=models.DateTimeField(
                blank=True,
                help_text="When this version was deployed to production",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="modelversion",
            name="deployed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="deployed_model_versions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="modelversion",
            name="deployment_config",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Deployment configuration (endpoint, resources, etc.)",
            ),
        ),
        migrations.AddField(
            model_name="modelversion",
            name="deployment_status",
            field=models.CharField(
                choices=[
                    ("none", "Not Deployed"),
                    ("staging", "Staging"),
                    ("production", "Production"),
                    ("retired", "Retired"),
                ],
                default="none",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="modelversion",
            name="error_message",
            field=models.TextField(
                blank=True, help_text="Error message if training failed"
            ),
        ),
        migrations.AddField(
            model_name="modelversion",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="modelversion",
            name="onnx_model_key",
            field=models.CharField(
                blank=True, help_text="Storage key for ONNX model", max_length=500
            ),
        ),
        migrations.AddField(
            model_name="modelversion",
            name="parent_version",
            field=models.ForeignKey(
                blank=True,
                help_text="Base version for transfer learning/fine-tuning",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="derived_versions",
                to="ml_models.modelversion",
            ),
        ),
        migrations.AddField(
            model_name="modelversion",
            name="storage_profile",
            field=models.ForeignKey(
                default=1,
                help_text="Storage profile where artifacts are stored",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="model_versions",
                to="storage.storageprofile",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="modelversion",
            name="training_logs_key",
            field=models.CharField(
                blank=True,
                help_text="Storage key for training logs file",
                max_length=500,
            ),
        ),
        migrations.AddField(
            model_name="modelversion",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="modelversion",
            name="version_id",
            field=models.CharField(
                default=django.utils.timezone.now,
                help_text="Unique identifier for this version",
                max_length=255,
                unique=True,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="modelversion",
            name="version_name",
            field=models.CharField(
                blank=True,
                help_text="Optional human-readable version name",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="modelversion",
            name="version_number",
            field=models.PositiveIntegerField(
                default=1, help_text="Sequential version number (1, 2, 3, ...)"
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="model",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_models",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="model",
            name="description",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="model",
            name="framework",
            field=models.ForeignKey(
                help_text="Framework/architecture used",
                on_delete=django.db.models.deletion.PROTECT,
                to="ml_models.modelframework",
            ),
        ),
        migrations.AlterField(
            model_name="model",
            name="name",
            field=models.CharField(
                help_text="Human-readable model name", max_length=255
            ),
        ),
        migrations.AlterField(
            model_name="model",
            name="project",
            field=models.ForeignKey(
                help_text="Project this model belongs to",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ml_models",
                to="projects.project",
            ),
        ),
        migrations.AlterField(
            model_name="model",
            name="task",
            field=models.ForeignKey(
                help_text="Type of task this model performs",
                on_delete=django.db.models.deletion.PROTECT,
                to="ml_models.modeltask",
            ),
        ),
        migrations.AlterField(
            model_name="modelversion",
            name="config",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Training configuration (hyperparameters, etc.)",
            ),
        ),
        migrations.AlterField(
            model_name="modelversion",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_model_versions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="modelversion",
            name="dataset_version",
            field=models.ForeignKey(
                blank=True,
                help_text="Dataset version used for training",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="trained_models",
                to="projects.version",
            ),
        ),
        migrations.AlterField(
            model_name="modelversion",
            name="metrics",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Training metrics (loss, accuracy, mAP, etc.)",
            ),
        ),
        migrations.AlterField(
            model_name="modelversion",
            name="model",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="versions",
                to="ml_models.model",
            ),
        ),
        migrations.AlterField(
            model_name="modelversion",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("queued", "Queued"),
                    ("training", "Training"),
                    ("trained", "Trained"),
                    ("failed", "Failed"),
                    ("cancelled", "Cancelled"),
                ],
                default="draft",
                max_length=20,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="model",
            unique_together={("organization", "name")},
        ),
        migrations.AlterUniqueTogether(
            name="modeltag",
            unique_together={("organization", "name")},
        ),
        migrations.AlterUniqueTogether(
            name="modelversion",
            unique_together={("model", "version_number")},
        ),
        migrations.AddIndex(
            model_name="model",
            index=models.Index(
                fields=["organization", "project", "is_deleted"],
                name="ml_model_organiz_849dd5_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="model",
            index=models.Index(
                fields=["organization", "created_at"],
                name="ml_model_organiz_5fd26c_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="modeltag",
            index=models.Index(
                fields=["organization", "name"], name="model_tag_organiz_241afc_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="modelversion",
            index=models.Index(
                fields=["model", "version_number", "is_deleted"],
                name="model_versi_model_i_3e5ad4_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="modelversion",
            index=models.Index(
                fields=["status", "created_at"], name="model_versi_status_5af5b1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="modelversion",
            index=models.Index(
                fields=["deployment_status"], name="model_versi_deploym_8709e3_idx"
            ),
        ),
        migrations.AlterModelTable(
            name="modelversion",
            table="model_version",
        ),
        migrations.RemoveField(
            model_name="modelversion",
            name="checkpoint",
        ),
        migrations.RemoveField(
            model_name="modelversion",
            name="logs",
        ),
        migrations.RemoveField(
            model_name="modelversion",
            name="version",
        ),
    ]
