# Generated by Django 4.2 on 2025-12-22 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ml_models", "0006_alter_modelversion_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="model",
            name="default_config",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Default training config (batchSize, learningRate, epochs, optimizer, scheduler)",
            ),
        ),
    ]
