# Generated by Django 4.2 on 2025-12-24 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ml_models", "0007_model_default_config"),
    ]

    operations = [
        migrations.AddField(
            model_name="modelversion",
            name="tags",
            field=models.ManyToManyField(
                blank=True,
                help_text="Tags specific to this model version",
                related_name="model_versions",
                to="ml_models.modeltag",
            ),
        ),
    ]
