# Generated by Django 4.2 on 2026-05-04 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ml_models', '0008_modelversion_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelversion',
            name='model_size',
            field=models.CharField(blank=True, default='', help_text='Model size variant (nano, small, medium, large, xlarge)', max_length=20),
        ),
    ]
