# Generated by Django 4.2 on 2025-11-19 19:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0004_organization_is_vendor'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('activity', '0003_orgactivitysummary'),
        ('projects', '0026_projectimage_last_review_version_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('invoice_number', models.CharField(max_length=50, unique=True)),
                ('period_start', models.DateField(db_index=True)),
                ('period_end', models.DateField(db_index=True)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=12)),
                ('tax_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('total_annotations', models.PositiveIntegerField(default=0)),
                ('total_reviews', models.PositiveIntegerField(default=0)),
                ('total_actions', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending'), ('paid', 'Paid'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('issued_at', models.DateTimeField(blank=True, null=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('metadata', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client_organization', models.ForeignKey(help_text='Client receiving invoice', on_delete=django.db.models.deletion.PROTECT, related_name='invoices_received', to='organizations.organization')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='projects.project')),
                ('vendor_organization', models.ForeignKey(help_text='Vendor issuing invoice', on_delete=django.db.models.deletion.PROTECT, related_name='invoices_issued', to='organizations.organization')),
            ],
            options={
                'db_table': 'invoice',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BillingRateCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate_card_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(help_text='Rate card name', max_length=255)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('rate_new_annotation', models.DecimalField(decimal_places=4, default=0.05, help_text='Cost per new annotation created from scratch', max_digits=10)),
                ('rate_untouched_prediction', models.DecimalField(decimal_places=4, default=0.02, help_text='Cost per AI prediction accepted without changes', max_digits=10)),
                ('rate_minor_edit', models.DecimalField(decimal_places=4, default=0.03, help_text='Cost per minor edit to prediction (resize, small adjustment)', max_digits=10)),
                ('rate_major_edit', models.DecimalField(decimal_places=4, default=0.04, help_text='Cost per major edit to prediction (significant change)', max_digits=10)),
                ('rate_class_change', models.DecimalField(decimal_places=4, default=0.04, help_text='Cost per class label change', max_digits=10)),
                ('rate_deletion', models.DecimalField(decimal_places=4, default=0.02, help_text='Cost per annotation deleted (removing false positive)', max_digits=10)),
                ('rate_missed_object', models.DecimalField(decimal_places=4, default=0.05, help_text='Cost per missed object added (finding false negative)', max_digits=10)),
                ('rate_image_review', models.DecimalField(decimal_places=4, default=0.1, help_text='Cost per image reviewed', max_digits=10)),
                ('rate_annotation_review', models.DecimalField(decimal_places=4, default=0.01, help_text='Cost per annotation reviewed', max_digits=10)),
                ('quality_bonus_threshold', models.DecimalField(decimal_places=2, default=95.0, help_text='Quality score % for bonus eligibility', max_digits=5)),
                ('quality_bonus_multiplier', models.DecimalField(decimal_places=2, default=1.1, help_text='Multiplier when quality threshold met (1.1 = 10% bonus)', max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(help_text='Vendor organization providing services', on_delete=django.db.models.deletion.CASCADE, related_name='billing_rate_cards', to='organizations.organization')),
                ('project', models.ForeignKey(blank=True, help_text='Project-specific rates (null = default rates)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='billing_rate_cards', to='projects.project')),
            ],
            options={
                'db_table': 'billing_rate_card',
            },
        ),
        migrations.CreateModel(
            name='BillableAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('action_type', models.CharField(choices=[('new_annotation', 'New Annotation'), ('untouched_prediction', 'Untouched Prediction'), ('minor_edit', 'Minor Edit'), ('major_edit', 'Major Edit'), ('class_change', 'Class Change'), ('deletion', 'Deletion'), ('missed_object', 'Missed Object'), ('image_review', 'Image Review'), ('annotation_review', 'Annotation Review')], db_index=True, max_length=30)),
                ('quantity', models.PositiveIntegerField(default=1, help_text='Number of units (annotations, reviews, etc)')),
                ('unit_rate', models.DecimalField(decimal_places=4, max_digits=10)),
                ('subtotal', models.DecimalField(decimal_places=4, max_digits=12)),
                ('quality_multiplier', models.DecimalField(decimal_places=2, default=1.0, max_digits=5)),
                ('total_amount', models.DecimalField(decimal_places=4, max_digits=12)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('metadata', models.JSONField(default=dict, help_text='Additional context (annotation_id, image_id, edit_magnitude, etc)')),
                ('is_billable', models.BooleanField(db_index=True, default=True, help_text='Can be excluded if action is free/internal')),
                ('billed_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('activity_event', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='billable_actions', to='activity.activityevent')),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='billable_actions', to='billing.invoice')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizations.organization')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.project')),
                ('rate_card', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='billable_actions', to='billing.billingratecard')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'billable_action',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['vendor_organization', 'period_start'], name='invoice_vendor__06264f_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['client_organization', 'status'], name='invoice_client__1f9625_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['status', 'due_date'], name='invoice_status_bad8ac_idx'),
        ),
        migrations.AddIndex(
            model_name='billingratecard',
            index=models.Index(fields=['organization', 'is_active'], name='billing_rat_organiz_6edcf7_idx'),
        ),
        migrations.AddIndex(
            model_name='billingratecard',
            index=models.Index(fields=['project', 'is_active'], name='billing_rat_project_9b0618_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='billingratecard',
            unique_together={('organization', 'project', 'name')},
        ),
        migrations.AddIndex(
            model_name='billableaction',
            index=models.Index(fields=['organization', 'created_at'], name='billable_ac_organiz_98b403_idx'),
        ),
        migrations.AddIndex(
            model_name='billableaction',
            index=models.Index(fields=['project', 'created_at'], name='billable_ac_project_32fd31_idx'),
        ),
        migrations.AddIndex(
            model_name='billableaction',
            index=models.Index(fields=['user', 'created_at'], name='billable_ac_user_id_1a8586_idx'),
        ),
        migrations.AddIndex(
            model_name='billableaction',
            index=models.Index(fields=['is_billable', 'billed_at'], name='billable_ac_is_bill_edea23_idx'),
        ),
        migrations.AddIndex(
            model_name='billableaction',
            index=models.Index(fields=['action_type', 'created_at'], name='billable_ac_action__16265e_idx'),
        ),
    ]
