# Generated by Django 4.2 on 2025-02-01 10:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0010_alter_versionimage_version'),
    ]

    operations = [
        migrations.CreateModel(
            name='Augmentation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Augmentations',
                'db_table': 'augmentation',
            },
        ),
        migrations.CreateModel(
            name='AugmentationParameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('parameter_type', models.CharField(choices=[('float', 'Float'), ('int', 'Integer'), ('bool', 'Boolean'), ('choice', 'Choice')], max_length=10)),
                ('choices', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Augmentation Parameters',
                'db_table': 'augmentation_parameter',
            },
        ),
        migrations.CreateModel(
            name='DatasetAugmentation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('augmentations', models.ManyToManyField(related_name='datasets', to='augmentations.augmentation')),
                ('version', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dataset_augmentation', to='projects.version')),
            ],
            options={
                'verbose_name_plural': 'Dataset Augmentations',
                'db_table': 'dataset_augmentation',
            },
        ),
        migrations.CreateModel(
            name='DatasetAugmentationParameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('augmentation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dataset_parameters', to='augmentations.augmentation')),
                ('dataset_augmentation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_parameters', to='augmentations.datasetaugmentation')),
                ('parameter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dataset_values', to='augmentations.augmentationparameter')),
            ],
            options={
                'verbose_name_plural': 'Dataset Augmentation Parameters',
                'db_table': 'dataset_augmentation_parameter',
            },
        ),
        migrations.CreateModel(
            name='AugmentationParameterAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_value', models.CharField(max_length=50)),
                ('min_value', models.FloatField(blank=True, null=True)),
                ('max_value', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('augmentation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_parameters', to='augmentations.augmentation')),
                ('parameter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_augmentations', to='augmentations.augmentationparameter')),
            ],
            options={
                'verbose_name_plural': 'Augmentation Parameter Assignments',
                'db_table': 'augmentation_parameter_assignment',
            },
        ),
    ]
