# Generated by Django 4.2 on 2025-02-01 21:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('augmentations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='augmentation',
            name='title',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
