# Generated by Django 4.2 on 2025-02-02 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('augmentations', '0002_augmentation_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='augmentation',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='augmentations/'),
        ),
    ]
