# Generated by Django 4.2 on 2025-03-27 14:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0014_projectimage_is_active'),
        ('augmentations', '0003_augmentation_thumbnail'),
    ]

    operations = [
        migrations.CreateModel(
            name='VersionImageAugmentation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('augmentation_name', models.CharField(max_length=100)),
                ('parameters', models.JSONField(blank=True, null=True)),
                ('augmented_image_file', models.FileField(blank=True, null=True, upload_to='versions/augmentations/')),
                ('augmented_annotation', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('version_image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='augmentations', to='projects.versionimage')),
            ],
            options={
                'verbose_name_plural': 'Version Image Augmentations',
                'db_table': 'version_image_augmentation',
            },
        ),
    ]
