# Generated by Django 4.2 on 2025-03-27 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('augmentations', '0005_alter_versionimageaugmentation_augmentation_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='versionimageaugmentation',
            name='augmented_image_file',
            field=models.ImageField(blank=True, null=True, upload_to='versions/augmentations/'),
        ),
    ]
