# Generated by Django 4.2 on 2025-03-27 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('augmentations', '0006_alter_versionimageaugmentation_augmented_image_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='versionimageaugmentation',
            name='augmented_image_file',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='versions/augmentations/'),
        ),
    ]
