# Generated by Django 4.2 on 2026-01-29 19:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0026_projectimage_last_review_version_and_more'),
        ('ml_models', '0008_modelversion_tags'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MetricSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('snapshot_date', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('total_images', models.IntegerField(default=0)),
                ('reviewed_images', models.IntegerField(default=0)),
                ('total_annotations', models.IntegerField(default=0)),
                ('precision', models.FloatField(default=0.0)),
                ('recall', models.FloatField(default=0.0)),
                ('f1_score', models.FloatField(default=0.0)),
                ('tp', models.IntegerField(default=0)),
                ('fp', models.IntegerField(default=0)),
                ('fn', models.IntegerField(default=0)),
                ('edit_rate', models.FloatField(default=0.0)),
                ('hallucination_rate', models.FloatField(default=0.0)),
                ('mean_confidence', models.FloatField(blank=True, null=True)),
                ('mean_localization_iou', models.FloatField(blank=True, null=True)),
                ('computation_time_seconds', models.FloatField(default=0.0)),
                ('model_version', models.ForeignKey(blank=True, help_text='Specific model version being evaluated', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='metric_snapshots', to='ml_models.modelversion')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metric_snapshots', to='projects.project')),
            ],
            options={
                'db_table': 'metric_snapshot',
                'ordering': ['-snapshot_date'],
            },
        ),
        migrations.CreateModel(
            name='MetricAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_date', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('severity', models.CharField(choices=[('critical', 'Critical'), ('warning', 'Warning'), ('info', 'Info')], max_length=20)),
                ('metric_name', models.CharField(max_length=50)),
                ('current_value', models.FloatField()),
                ('previous_value', models.FloatField(blank=True, null=True)),
                ('threshold_value', models.FloatField()),
                ('change_percent', models.FloatField(blank=True, null=True)),
                ('is_acknowledged', models.BooleanField(db_index=True, default=False)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('message', models.TextField()),
                ('acknowledged_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acknowledged_alerts', to=settings.AUTH_USER_MODEL)),
                ('model_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='metric_alerts', to='ml_models.modelversion')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metric_alerts', to='projects.project')),
            ],
            options={
                'db_table': 'metric_alert',
                'ordering': ['-alert_date'],
            },
        ),
        migrations.AddIndex(
            model_name='metricsnapshot',
            index=models.Index(fields=['project', 'model_version', 'snapshot_date'], name='metric_snap_project_5aea29_idx'),
        ),
        migrations.AddIndex(
            model_name='metricsnapshot',
            index=models.Index(fields=['project', '-snapshot_date'], name='metric_snap_project_45e3ba_idx'),
        ),
        migrations.AddIndex(
            model_name='metricalert',
            index=models.Index(fields=['project', 'is_acknowledged'], name='metric_aler_project_3d1991_idx'),
        ),
        migrations.AddIndex(
            model_name='metricalert',
            index=models.Index(fields=['severity', '-alert_date'], name='metric_aler_severit_2c59fb_idx'),
        ),
    ]
