# Generated by Django 4.2 on 2025-06-17 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inferences', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='predictionoverlay',
            name='class_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
