# Generated by Django 4.2 on 2026-04-25 07:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ml_models', '0008_modelversion_tags'),
        ('projects', '0026_projectimage_last_review_version_and_more'),
        ('inferences', '0002_predictionoverlay_class_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evaluation_id', models.CharField(max_length=255, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], db_index=True, default='pending', max_length=20)),
                ('challenger_metrics', models.JSONField(blank=True, default=dict)),
                ('champion_metrics', models.JSONField(blank=True, default=dict)),
                ('primary_metric', models.CharField(default='f1_score', help_text='Metric key used for champion/challenger comparison', max_length=100)),
                ('improvement_delta', models.FloatField(blank=True, help_text='challenger_metric - champion_metric (positive = improvement)', null=True)),
                ('auto_promote_threshold', models.FloatField(default=0.02, help_text='Minimum delta required to auto-promote challenger')),
                ('recommendation', models.CharField(blank=True, choices=[('promote', 'Promote Challenger'), ('keep_champion', 'Keep Champion'), ('inconclusive', 'Inconclusive')], max_length=20, null=True)),
                ('auto_promoted', models.BooleanField(default=False)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('challenger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='challenger_evaluations', to='ml_models.modelversion')),
                ('champion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='champion_evaluations', to='ml_models.modelversion')),
                ('dataset_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='model_evaluations', to='projects.version')),
                ('triggered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Model Evaluations',
                'db_table': 'model_evaluation',
            },
        ),
        migrations.CreateModel(
            name='InferenceDeployment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_env', models.CharField(choices=[('staging', 'Staging'), ('production', 'Production')], default='staging', max_length=20)),
                ('inference_service_url', models.CharField(max_length=500)),
                ('deployed_at', models.DateTimeField(auto_now_add=True)),
                ('undeployed_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('deployed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('model_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deployments', to='ml_models.modelversion')),
            ],
            options={
                'verbose_name_plural': 'Inference Deployments',
                'db_table': 'inference_deployment',
            },
        ),
        migrations.AddIndex(
            model_name='modelevaluation',
            index=models.Index(fields=['challenger', 'status'], name='model_evalu_challen_0fc4bd_idx'),
        ),
        migrations.AddIndex(
            model_name='modelevaluation',
            index=models.Index(fields=['status', 'created_at'], name='model_evalu_status_cd8ebe_idx'),
        ),
        migrations.AddIndex(
            model_name='inferencedeployment',
            index=models.Index(fields=['model_version', 'is_active'], name='inference_d_model_v_30f5be_idx'),
        ),
    ]
