# Generated by Django 4.2 on 2026-04-15 19:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('organizations', '0004_organization_is_vendor'),
        ('projects', '0026_projectimage_last_review_version_and_more'),
        ('images', '0010_alter_image_image_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='SimilarityCluster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cluster_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('member_count', models.PositiveIntegerField(db_index=True, default=0, help_text='Total images in this cluster (including representative)')),
                ('avg_similarity', models.FloatField(blank=True, help_text='Average pairwise similarity score (0.0–1.0)', null=True)),
                ('max_similarity', models.FloatField(blank=True, null=True)),
                ('status', models.CharField(choices=[('unreviewed', 'Unreviewed'), ('reviewed', 'Reviewed'), ('actioned', 'Actioned')], db_index=True, default='unreviewed', max_length=20)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('representative', models.ForeignKey(help_text='The image chosen as the keeper for this cluster', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='representative_in_clusters', to='images.image')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_clusters', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Similarity Cluster',
                'verbose_name_plural': 'Similarity Clusters',
                'db_table': 'similarity_cluster',
                'ordering': ['-member_count', '-avg_similarity'],
            },
        ),
        migrations.CreateModel(
            name='SimilarityScan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scan_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='Public-facing scan identifier', unique=True)),
                ('scope', models.CharField(choices=[('datalake', 'Entire Datalake'), ('project', 'Single Project')], default='datalake', help_text='Whether scan covers the datalake or a single project', max_length=20)),
                ('algorithm', models.CharField(choices=[('ahash', 'Average Hash (fast)'), ('phash', 'Perceptual Hash (robust)'), ('dhash', 'Difference Hash (crop-tolerant)'), ('whash', 'Wavelet Hash (accurate)')], default='ahash', help_text='Perceptual hash algorithm used', max_length=10)),
                ('threshold', models.PositiveSmallIntegerField(default=6, help_text='Hamming distance threshold (0=exact, 64=anything)')),
                ('similarity_threshold', models.FloatField(default=0.8, help_text='Similarity threshold as fraction 0.0–1.0')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], db_index=True, default='pending', max_length=20)),
                ('total_images', models.PositiveIntegerField(default=0)),
                ('hashed_images', models.PositiveIntegerField(default=0)),
                ('clusters_found', models.PositiveIntegerField(default=0)),
                ('task_id', models.CharField(blank=True, help_text='Celery task ID', max_length=255, null=True)),
                ('error_log', models.TextField(blank=True, help_text='Error detail if scan failed', null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('initiated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='initiated_scans', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(help_text='Organization that owns this scan', on_delete=django.db.models.deletion.CASCADE, related_name='similarity_scans', to='organizations.organization')),
                ('project', models.ForeignKey(blank=True, help_text='Project scope (null = entire datalake)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='similarity_scans', to='projects.project')),
            ],
            options={
                'verbose_name': 'Similarity Scan',
                'verbose_name_plural': 'Similarity Scans',
                'db_table': 'similarity_scan',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SimilarityClusterMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('representative', 'Representative'), ('duplicate', 'Duplicate')], db_index=True, default='duplicate', max_length=20)),
                ('similarity_score', models.FloatField(help_text='Similarity to cluster representative (1.0 = identical)')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('cluster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='similarity.similaritycluster')),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cluster_memberships', to='images.image')),
            ],
            options={
                'verbose_name': 'Cluster Member',
                'verbose_name_plural': 'Cluster Members',
                'db_table': 'similarity_cluster_member',
            },
        ),
        migrations.AddField(
            model_name='similaritycluster',
            name='scan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clusters', to='similarity.similarityscan'),
        ),
        migrations.CreateModel(
            name='ImageHash',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('algorithm', models.CharField(choices=[('ahash', 'Average Hash (fast)'), ('phash', 'Perceptual Hash (robust)'), ('dhash', 'Difference Hash (crop-tolerant)'), ('whash', 'Wavelet Hash (accurate)')], help_text='Hash algorithm used', max_length=10)),
                ('hash_value', models.CharField(help_text='Hex-encoded hash string', max_length=256)),
                ('computed_at', models.DateTimeField(auto_now_add=True)),
                ('image', models.ForeignKey(help_text='Image this hash belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='perceptual_hashes', to='images.image')),
            ],
            options={
                'verbose_name': 'Image Hash',
                'verbose_name_plural': 'Image Hashes',
                'db_table': 'similarity_image_hash',
            },
        ),
        migrations.CreateModel(
            name='ClusterAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('action_type', models.CharField(choices=[('archive_duplicates', 'Archive Duplicates'), ('delete_duplicates', 'Delete Duplicates'), ('mark_reviewed', 'Mark Reviewed'), ('set_representative', 'Set Representative'), ('remove_from_cluster', 'Remove from Cluster')], max_length=30)),
                ('image_ids', models.JSONField(default=list, help_text='Image IDs affected by this action')),
                ('meta', models.JSONField(blank=True, default=dict)),
                ('performed_at', models.DateTimeField(auto_now_add=True)),
                ('cluster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='similarity.similaritycluster')),
                ('performed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cluster_actions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cluster Action',
                'verbose_name_plural': 'Cluster Actions',
                'db_table': 'similarity_cluster_action',
                'ordering': ['-performed_at'],
            },
        ),
        migrations.AddIndex(
            model_name='similarityscan',
            index=models.Index(fields=['organization', 'status'], name='similarity__organiz_28039a_idx'),
        ),
        migrations.AddIndex(
            model_name='similarityscan',
            index=models.Index(fields=['organization', 'project'], name='similarity__organiz_42a6f7_idx'),
        ),
        migrations.AddIndex(
            model_name='similarityscan',
            index=models.Index(fields=['scan_id'], name='similarity__scan_id_22d6ba_idx'),
        ),
        migrations.AddIndex(
            model_name='similarityclustermember',
            index=models.Index(fields=['cluster', 'role'], name='similarity__cluster_8f3ece_idx'),
        ),
        migrations.AddIndex(
            model_name='similarityclustermember',
            index=models.Index(fields=['image'], name='similarity__image_i_87e71a_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='similarityclustermember',
            unique_together={('cluster', 'image')},
        ),
        migrations.AddIndex(
            model_name='similaritycluster',
            index=models.Index(fields=['scan', 'status'], name='similarity__scan_id_c36081_idx'),
        ),
        migrations.AddIndex(
            model_name='similaritycluster',
            index=models.Index(fields=['scan', 'member_count'], name='similarity__scan_id_a6e65b_idx'),
        ),
        migrations.AddIndex(
            model_name='imagehash',
            index=models.Index(fields=['algorithm', 'image'], name='similarity__algorit_1e3167_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='imagehash',
            unique_together={('image', 'algorithm')},
        ),
        migrations.AddIndex(
            model_name='clusteraction',
            index=models.Index(fields=['cluster', 'performed_at'], name='similarity__cluster_a44625_idx'),
        ),
        migrations.AddIndex(
            model_name='clusteraction',
            index=models.Index(fields=['performed_by'], name='similarity__perform_39d72e_idx'),
        ),
    ]
