# Generated by Django 4.2 on 2024-12-18 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_imagemode_projectimage_mode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectimage',
            name='annotations',
        ),
    ]
