# Generated by Django 4.2 on 2025-01-06 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_project_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectimage',
            name='reviewed',
            field=models.BooleanField(default=False),
        ),
    ]
