# Generated by Django 4.2 on 2025-01-12 19:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_projectimage_reviewed'),
    ]

    operations = [
        migrations.CreateModel(
            name='Version',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_name', models.CharField(max_length=100, unique=True)),
                ('version_number', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='projects.project')),
            ],
            options={
                'verbose_name_plural': 'Versions',
                'db_table': 'version',
                'ordering': ['version_number'],
                'unique_together': {('project', 'version_number')},
            },
        ),
        migrations.CreateModel(
            name='VersionImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('project_image', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='associated_versions', to='projects.projectimage')),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='version_images', to='projects.version')),
            ],
            options={
                'verbose_name_plural': 'Version Images',
                'db_table': 'version_image',
                'unique_together': {('version', 'project_image')},
            },
        ),
    ]
