# Generated by Django 4.2 on 2025-01-28 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_alter_version_version_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectimage',
            name='finalized',
            field=models.BooleanField(default=False),
        ),
    ]
