# Generated by Django 4.2 on 2025-01-29 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_projectimage_finalized'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectimage',
            name='status',
            field=models.CharField(choices=[('unannotated', 'Unannotated'), ('annotated', 'Annotated'), ('reviewed', 'Reviewed'), ('dataset', 'Dataset')], default='unannotated', max_length=20),
        ),
    ]
