# Generated by Django 4.2 on 2025-02-03 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0010_alter_versionimage_version'),
    ]

    operations = [
        migrations.AddField(
            model_name='version',
            name='version_file',
            field=models.FileField(blank=True, null=True, upload_to='versions/'),
        ),
    ]
