# Generated by Django 4.2 on 2025-03-11 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0012_projectimage_feedback_provided'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectimage',
            name='marked_as_null',
            field=models.BooleanField(default=False),
        ),
    ]
