# Generated by Django 4.2 on 2025-03-13 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0013_projectimage_marked_as_null'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectimage',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
