# Generated by Django 4.2 on 2025-10-06 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0016_projectimage_job_assignment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectimage',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
