# Generated by Django 4.2 on 2025-10-23 16:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import projects.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0003_alter_organization_options_organization_created_by_and_more'),
        ('images', '0008_alter_image_options_alter_tag_options_image_checksum_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0017_projectimage_updated_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['-last_edited', '-created_at'], 'verbose_name': 'Project', 'verbose_name_plural': 'Projects'},
        ),
        migrations.AlterModelOptions(
            name='projectimage',
            options={'ordering': ['-priority', '-added_at'], 'verbose_name': 'Project Image', 'verbose_name_plural': 'Project Images'},
        ),
        migrations.AlterModelOptions(
            name='projecttype',
            options={'ordering': ['name'], 'verbose_name': 'Project Type', 'verbose_name_plural': 'Project Types'},
        ),
        migrations.AlterModelOptions(
            name='visibility',
            options={'ordering': ['display_order', 'name'], 'verbose_name': 'Visibility', 'verbose_name_plural': 'Visibility Options'},
        ),
        migrations.AddField(
            model_name='project',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='User who created this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='project',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects_deleted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='project',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False, help_text='Soft delete flag'),
        ),
        migrations.AddField(
            model_name='project',
            name='project_id',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='Unique identifier for the project', unique=True),
        ),
        migrations.AddField(
            model_name='project',
            name='settings',
            field=models.JSONField(blank=True, default=dict, help_text='Project-specific settings and configurations'),
        ),
        migrations.AddField(
            model_name='project',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='project',
            name='updated_by',
            field=models.ForeignKey(blank=True, help_text='User who last updated this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='projectimage',
            name='added_by',
            field=models.ForeignKey(blank=True, help_text='User who added image to project', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='added_project_images', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='projectimage',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, help_text='Additional metadata (annotation stats, quality scores, etc.)'),
        ),
        migrations.AddField(
            model_name='projectimage',
            name='priority',
            field=models.IntegerField(default=0, help_text='Priority for annotation (higher = more important)'),
        ),
        migrations.AddField(
            model_name='projectimage',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, help_text='When annotations were reviewed', null=True),
        ),
        migrations.AddField(
            model_name='projectimage',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, help_text='User who reviewed the annotations', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_project_images', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='projecttype',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='User who created this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='projecttype',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AddField(
            model_name='projecttype',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='projecttype',
            name='updated_by',
            field=models.ForeignKey(blank=True, help_text='User who last updated this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='visibility',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='User who created this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='visibility',
            name='display_order',
            field=models.IntegerField(default=0, help_text='Order in which visibility options are displayed'),
        ),
        migrations.AddField(
            model_name='visibility',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='visibility',
            name='updated_by',
            field=models.ForeignKey(blank=True, help_text='User who last updated this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='project',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, help_text='Whether the project is active or archived'),
        ),
        migrations.AlterField(
            model_name='project',
            name='last_edited',
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(help_text='Human-readable project name', max_length=255),
        ),
        migrations.AlterField(
            model_name='project',
            name='organization',
            field=models.ForeignKey(default=1, help_text='Organization that owns this project', on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='organizations.organization'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='project',
            name='project_type',
            field=models.ForeignKey(default=1, help_text='Type of computer vision task', on_delete=django.db.models.deletion.PROTECT, related_name='projects', to='projects.projecttype'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='project',
            name='thumbnail_url',
            field=models.URLField(blank=True, help_text='URL to project thumbnail image', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='visibility',
            field=models.ForeignKey(default=projects.models.get_default_visibility, help_text='Who can view this project', on_delete=django.db.models.deletion.PROTECT, related_name='projects', to='projects.visibility'),
        ),
        migrations.AlterField(
            model_name='projectimage',
            name='added_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='projectimage',
            name='annotated',
            field=models.BooleanField(db_index=True, default=False, help_text='Whether image has been annotated in this project'),
        ),
        migrations.AlterField(
            model_name='projectimage',
            name='feedback_provided',
            field=models.BooleanField(default=False, help_text='Whether feedback has been provided'),
        ),
        migrations.AlterField(
            model_name='projectimage',
            name='finalized',
            field=models.BooleanField(default=False, help_text='Whether image is finalized for use'),
        ),
        migrations.AlterField(
            model_name='projectimage',
            name='image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_assignments', to='images.image'),
        ),
        migrations.AlterField(
            model_name='projectimage',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, help_text='Whether this assignment is active'),
        ),
        migrations.AlterField(
            model_name='projectimage',
            name='job_assignment_status',
            field=models.CharField(choices=[('assigned', 'Assigned to job'), ('waiting', 'Waiting for job'), ('excluded', 'Excluded from job assignment')], db_index=True, default='waiting', help_text='Job assignment status', max_length=20),
        ),
        migrations.AlterField(
            model_name='projectimage',
            name='marked_as_null',
            field=models.BooleanField(default=False, help_text='Whether image is marked as unusable/null'),
        ),
        migrations.AlterField(
            model_name='projectimage',
            name='mode',
            field=models.ForeignKey(blank=True, help_text='Optional image mode/category', null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.imagemode'),
        ),
        migrations.AlterField(
            model_name='projectimage',
            name='reviewed',
            field=models.BooleanField(default=False, help_text='Whether annotations have been reviewed'),
        ),
        migrations.AlterField(
            model_name='projectimage',
            name='status',
            field=models.CharField(choices=[('unannotated', 'Unannotated'), ('in_progress', 'In Progress'), ('annotated', 'Annotated'), ('reviewed', 'Reviewed'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('dataset', 'Ready for Dataset')], db_index=True, default='unannotated', max_length=20),
        ),
        migrations.AlterField(
            model_name='projecttype',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='projecttype',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='projecttype',
            name='meta_info',
            field=models.JSONField(blank=True, help_text='Additional metadata about project type configuration', null=True),
        ),
        migrations.AlterField(
            model_name='projecttype',
            name='name',
            field=models.CharField(db_index=True, max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='visibility',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='visibility',
            name='name',
            field=models.CharField(db_index=True, max_length=50, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='project',
            unique_together={('organization', 'name')},
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['organization', 'is_active', 'is_deleted'], name='project_organiz_df0f75_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['organization', 'project_type'], name='project_organiz_e6f20d_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['visibility', 'is_active'], name='project_visibil_ded83a_idx'),
        ),
        migrations.AddIndex(
            model_name='projectimage',
            index=models.Index(fields=['project', 'status'], name='project_ima_project_a02366_idx'),
        ),
        migrations.AddIndex(
            model_name='projectimage',
            index=models.Index(fields=['project', 'annotated'], name='project_ima_project_c2356e_idx'),
        ),
        migrations.AddIndex(
            model_name='projectimage',
            index=models.Index(fields=['project', 'is_active'], name='project_ima_project_97895a_idx'),
        ),
        migrations.AddIndex(
            model_name='projectimage',
            index=models.Index(fields=['project', 'job_assignment_status'], name='project_ima_project_e499cc_idx'),
        ),
        migrations.AddIndex(
            model_name='projectimage',
            index=models.Index(fields=['added_at'], name='project_ima_added_a_b72a95_idx'),
        ),
    ]
