# Generated by Django 4.2 on 2025-11-03 18:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0018_alter_project_options_alter_projectimage_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='version',
            options={'ordering': ['version_number'], 'verbose_name': 'Dataset Version', 'verbose_name_plural': 'Dataset Versions'},
        ),
        migrations.RemoveField(
            model_name='version',
            name='version_file',
        ),
        migrations.AddField(
            model_name='version',
            name='class_distribution',
            field=models.JSONField(blank=True, default=dict, help_text='Class distribution stats'),
        ),
        migrations.AddField(
            model_name='version',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='User who created this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='version',
            name='dataset_file',
            field=models.FileField(blank=True, help_text='Exported dataset file (zip)', null=True, upload_to='datasets/'),
        ),
        migrations.AddField(
            model_name='version',
            name='download_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='version',
            name='error_log',
            field=models.TextField(blank=True, help_text='Error log if export failed', null=True),
        ),
        migrations.AddField(
            model_name='version',
            name='export_config',
            field=models.JSONField(blank=True, default=dict, help_text='Export configuration (image size, augmentation, etc.)'),
        ),
        migrations.AddField(
            model_name='version',
            name='export_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], db_index=True, default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='version',
            name='exported_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='version',
            name='file_size',
            field=models.BigIntegerField(blank=True, help_text='Dataset file size in bytes', null=True),
        ),
        migrations.AddField(
            model_name='version',
            name='storage_key',
            field=models.CharField(blank=True, help_text='Cloud storage key if uploaded to S3/Azure', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='version',
            name='test_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='version',
            name='total_annotations',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='version',
            name='total_images',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='version',
            name='train_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='version',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='version',
            name='updated_by',
            field=models.ForeignKey(blank=True, help_text='User who last updated this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='version',
            name='val_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='version',
            name='version_id',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AddField(
            model_name='versionimage',
            name='annotation_count',
            field=models.PositiveIntegerField(default=0, help_text='Number of annotations on this image'),
        ),
        migrations.AddField(
            model_name='versionimage',
            name='included_in_export',
            field=models.BooleanField(default=True, help_text='Whether image was included in export'),
        ),
        migrations.AddField(
            model_name='versionimage',
            name='split',
            field=models.CharField(choices=[('train', 'Training'), ('val', 'Validation'), ('test', 'Test')], db_index=True, default='train', help_text='Dataset split (train/val/test)', max_length=10),
        ),
        migrations.AlterField(
            model_name='version',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AddIndex(
            model_name='version',
            index=models.Index(fields=['project', 'export_status'], name='version_project_158dd3_idx'),
        ),
        migrations.AddIndex(
            model_name='version',
            index=models.Index(fields=['version_id'], name='version_version_650829_idx'),
        ),
        migrations.AddIndex(
            model_name='versionimage',
            index=models.Index(fields=['version', 'split'], name='version_ima_version_0e7cf9_idx'),
        ),
    ]
