# Generated by Django 4.2 on 2025-11-03 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0019_alter_version_options_remove_version_version_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='version',
            name='export_format',
            field=models.CharField(choices=[('yolo', 'YOLO (txt)'), ('coco', 'COCO (json)'), ('pascal_voc', 'Pascal VOC (xml)'), ('tfrecord', 'TFRecord'), ('custom', 'Custom Format')], default='yolo', max_length=20),
        ),
    ]
