# Generated by Django 4.2 on 2025-11-06 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0020_version_export_format'),
    ]

    operations = [
        migrations.AlterField(
            model_name='versionimage',
            name='split',
            field=models.CharField(choices=[('train', 'Training'), ('valid', 'Validation'), ('test', 'Test')], db_index=True, default='train', help_text='Dataset split (train/val/test)', max_length=10),
        ),
    ]
