# Generated by Django 4.2 on 2025-11-08 16:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0001_initial'),
        ('projects', '0022_alter_versionimage_split'),
    ]

    operations = [
        migrations.AddField(
            model_name='version',
            name='storage_profile',
            field=models.ForeignKey(default=1, help_text='Storage profile where this image is stored', on_delete=django.db.models.deletion.PROTECT, related_name='versions', to='storage.storageprofile'),
            preserve_default=False,
        ),
    ]
