# Generated by Django 4.2 on 2025-11-08 16:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0001_initial'),
        ('projects', '0023_version_storage_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='version',
            name='storage_profile',
            field=models.ForeignKey(help_text='Storage profile where this image is stored', on_delete=django.db.models.deletion.PROTECT, related_name='dataset_versions', to='storage.storageprofile'),
        ),
    ]
