# Generated by Django 4.2 on 2025-11-11 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0024_alter_version_storage_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectimage',
            name='review_count',
            field=models.IntegerField(default=0, help_text='count of time the image is reviewed)'),
        ),
    ]
