# Generated by Django 4.2 on 2025-11-11 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0025_projectimage_review_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectimage',
            name='last_review_version',
            field=models.PositiveIntegerField(default=0, help_text='Version number of last review'),
        ),
        migrations.AlterField(
            model_name='projectimage',
            name='review_count',
            field=models.PositiveIntegerField(default=0, help_text='Number of times this image has been reviewed'),
        ),
    ]
