"""
Django settings for perceptra_hub project.

Generated by 'django-admin startproject' using Django 4.2.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""
import os
from pathlib import Path
from django.templatetags.static import static
from django.urls import reverse_lazy
from django.utils.translation import gettext_lazy as _

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-edvpp4+wx19+(o+k-9+yd)l=s&yvg!j(0bv^+npq-yve0lmj$*'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'unfold',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'storages',
    'users',
    'metadata',
    'tenants',
    'images',
    'projects',
    'annotations',
    'augmentations',
    'organizations',
    'memberships',
    'jobs',
    'ml_models',
    'training',
    'inferences',
    'storage',
    'activity',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'perceptra_hub.urls'
AUTH_USER_MODEL = "users.CustomUser"

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'perceptra_hub.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': os.environ.get('DATABASE_ENGINE', "django.db.backends.sqlite3"),
        'NAME': os.environ.get('DATABASE_NAME') if not 'sqlite3' in os.environ.get('DATABASE_ENGINE') else BASE_DIR / 'db.sqlite3',
        'USER': os.environ.get('DATABASE_USER'),
        'PASSWORD': os.environ.get('DATABASE_PASSWD'),
        'HOST': os.environ.get('DATABASE_HOST'),
        'PORT': os.environ.get('DATABASE_PORT')

    }
}

CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.filebased.FileBasedCache',
        'LOCATION': '/var/tmp/django_cache',
    }
}

# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
EMAIL_HOST = "smtp.office365.com"
EMAIL_PORT = 587  # Or 465 for SSL
EMAIL_USE_TLS = True
EMAIL_HOST_USER = "no-reply@perceptra-hub.com"
EMAIL_HOST_PASSWORD = os.environ.get("EMAIL_HOST_PASSWORD")  # Use an env variable!
DEFAULT_FROM_EMAIL = EMAIL_HOST_USER
SECRET_ENCRYPTION_KEY = os.getenv("SECRET_ENCRYPTION_KEY")

# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
STATICFILES_DIRS = [os.path.join(BASE_DIR, 'static')]

MEDIA_URL = 'media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

UNFOLD = {
    "SITE_HEADER": _("PercetraHub"),
    "SITE_TITLE": _("Perception Hub"),
    "SITE_SYMBOL": "Perceptra",
    "SITE_ICON": {
        "light": lambda request: static("icon-light.svg"),  # light mode
        "dark": lambda request: static("icon-dark.svg"),  # dark mode
    },
    "SITE_LOGO": lambda request: static("images/logo.jpg"),  # both modes, optimise for 32px height
    # "SITE_LOGO": {
    #     "light": lambda request: static("logo-light.svg"),  # light mode
    #     "dark": lambda request: static("logo-dark.svg"),  # dark mode
    # },
    "SITE_SYMBOL": "speed",  # symbol from icon set
    "SITE_FAVICONS": [
        {
            "rel": "icon",
            "sizes": "46x32",
            "type": "image/svg+xml",
            "href": lambda request: static("favicon.svg"),
        },
    ],
    "SHOW_HISTORY": True, # show/hide "History" button, default: True
    "SHOW_VIEW_ON_SITE": True, # show/hide "View on site" button, default: True
    # "THEME": "dark", # Force theme: "dark" or "light". Will disable theme switcher
    "LOGIN": {
        "image": lambda request: static("images/login.jpeg"),
        "redirect_after": lambda request: reverse_lazy("admin:tenants_tenant_changelist"),
    },
    "EXTENSIONS": {
        "modeltranslation": {
            "flags": {
                "de": "🇩🇪",
                "en": "🇬🇧",
                "fr": "🇫🇷",
                "nl": "🇧🇪",
            },
        },
    },
    "SIDEBAR": {
        "show_search": True,
        "show_all_applications": True,
        "navigation": [
            {
                "title": _("Navigation"),
                "items": [
                    {
                        "title": _("All Apps"),
                        "icon": "dashboard",
                        "link": reverse_lazy("admin:index"),
                    },
                ]
            },
            # {
            #     "title": _("Tenant"),
            #     "collapsible": True,
            #     "items": [
            #         {
            #             "title": _("Tenant"),
            #             "icon": 'tenancy',
            #             "link": reverse_lazy(
            #                 "admin:tenants_tenant_changelist"
            #             ),
            #         },
            #         {
            #             "title": _("Plant"),
            #             "icon": 'local_fire_department',
            #             "link": reverse_lazy(
            #                 "admin:tenants_plant_changelist"
            #             ),
            #         },
            #         {
            #             "title": _("Domain"),
            #             "icon": 'domain',
            #             "link": reverse_lazy(
            #                 "admin:tenants_domain_changelist"
            #             ),
            #         },
            #         {
            #             "title": _("Edge Boxes"),
            #             "icon": 'devices',
            #             "link": reverse_lazy(
            #                 "admin:tenants_edgebox_changelist"
            #             ),
            #         },
            #         {
            #             "title": _("SensorBoxes"),
            #             "icon": 'sensors',
            #             "link": reverse_lazy(
            #                 "admin:tenants_sensorbox_changelist"
            #             ),
            #         },
            #     ]
            # },
            {
                "title": _("Users & Groups"),
                "collapsible": True,
                "items": [
                    {
                        "title": _("Users"),
                        "icon": "person",
                        "link": reverse_lazy(
                            "admin:users_customuser_changelist"
                            ),
                    },
                    {
                        "title": _("Groups"),
                        "icon": "group",
                        "link": reverse_lazy(
                            "admin:auth_group_changelist"
                            ),
                    }
                ],
            },
            {
                "title": _("Organizations Management"),
                "collapsible": True,
                "items": [
                    {
                        "title": _("Organizations"),
                        "icon": "domain",
                        "link": reverse_lazy(
                            "admin:organizations_organization_changelist"
                            ),
                    },
                ],
            },
            {
                "title": _("Storages"),
                "collapsible": True,
                "items": [
                    {
                        "title": _("Secret Ref"),
                        "icon": "key",
                        "link": reverse_lazy(
                            "admin:storage_secretref_changelist"
                            ),
                    },
                    {
                        "title": _("Enctrypted Secrets"),
                        "icon": "encrypted",
                        "link": reverse_lazy(
                            "admin:storage_encryptedsecret_changelist"
                            ),
                    },
                    {
                        "title": _("Storage Profile"),
                        "icon": "cloud_lock",
                        "link": reverse_lazy(
                            "admin:storage_storageprofile_changelist"
                            ),
                    },
                ],
            },
            {
                "title": _("Memberships"),
                "collapsible": True,
                "items": [
                    {
                        "title": _("Roles"),
                        "icon": "domain",
                        "link": reverse_lazy(
                            "admin:memberships_role_changelist"
                            ),
                    },
                    {
                        "title": _("Organization Memberships"),
                        "icon": "domain",
                        "link": reverse_lazy(
                            "admin:memberships_organizationmembership_changelist"
                            ),
                    },
                    {
                        "title": _("Project Memberships"),
                        "icon": "domain",
                        "link": reverse_lazy(
                            "admin:memberships_projectmembership_changelist"
                            ),
                    },
                ],
            },
            {
                "title": _("MetaData"),
                "collapsible": True,
                "items": [
                    {
                        "title": _("Languages"),
                        "icon": "language",
                        "link": reverse_lazy(
                            "admin:metadata_language_changelist"
                        ),
                    },
                ],
            },
            {
                "title": _("Images"),
                "collapsible": True,
                "items": [
                    {
                        "title": _("Images"),
                        "icon": 'image',
                        "link": reverse_lazy(
                            "admin:images_image_changelist"
                        ),
                    },
                ]
            },
            {
                "title": _("Projects"),
                "collapsible": True,
                "items": [
                    {
                        "title": _("Project Types"),
                        "icon": 'task',
                        "link": reverse_lazy(
                            "admin:projects_projecttype_changelist"
                        ),
                    },
                    {
                        "title": _("Visibility"),
                        "icon": 'visibility',
                        "link": reverse_lazy(
                            "admin:projects_visibility_changelist"
                        ),
                    },
                    {
                        "title": _("Project"),
                        "icon": 'tactic',
                        "link": reverse_lazy(
                            "admin:projects_project_changelist"
                        ),
                    },
                    {
                        "title": _("Project Metadata"),
                        "icon": 'menu',
                        "link": reverse_lazy(
                            "admin:projects_projectmetadata_changelist"
                        ),
                    },
                    {
                        "title": _("Image Mode"),
                        "icon": 'imagesmode',
                        "link": reverse_lazy(
                            "admin:projects_imagemode_changelist"
                        ),
                    },
                    {
                        "title": _("Project Images"),
                        "icon": 'image',
                        "link": reverse_lazy(
                            "admin:projects_projectimage_changelist"
                        ),
                    },
                    {
                        "title": _("Versions"),
                        "icon": 'folder',
                        "link": reverse_lazy(
                            "admin:projects_version_changelist"
                        ),
                    },
                ]
            },
            {
                "title": _("Jobs Management"),
                "collapsible": True,
                "items": [
                    {
                        "title": _("Jobs"),
                        "icon": "",
                        "link": reverse_lazy(
                            "admin:jobs_job_changelist"
                        )
                    },
                    {
                        "title": _("Job Images"),
                        "icon": "",
                        "link": reverse_lazy(
                            "admin:jobs_jobimage_changelist"
                        )
                    }
                ]
            },
            {
                "title": _("Annotations"),
                "collapsible": True,
                "items": [
                    {
                        "title": _("Annotation Groups"),
                        "icon": 'group_work',
                        "link": reverse_lazy(
                            "admin:annotations_annotationgroup_changelist"
                        ),
                    },
                    {
                        "title": _("Annotation Classes"),
                        "icon": 'hotel_class',
                        "link": reverse_lazy(
                            "admin:annotations_annotationclass_changelist"
                        ),
                    },
                    {
                        "title": _("Annotation Type"),
                        "icon": 'type_specimen',
                        "link": reverse_lazy(
                            "admin:annotations_annotationtype_changelist"
                        ),
                    },
                    {
                        "title": _("Annotations"),
                        "icon": 'tooltip',
                        "link": reverse_lazy(
                            "admin:annotations_annotation_changelist"
                        ),
                    },
                    {
                        "title": _("Annotation Audits"),
                        "icon": 'policy',
                        "link": reverse_lazy(
                            "admin:annotations_annotationaudit_changelist"
                        ),
                    },
                ]
            },
            {
                "title": _("Augmentations Manager"),
                "collapsible": True,
                "items": [
                    {
                        "title": _("Augmentations"),
                        "icon": '',
                        "link": reverse_lazy(
                            "admin:augmentations_augmentation_changelist"
                        ),
                    },
                    {
                        "title": _("Augmentation Parameters"),
                        "icon": '',
                        "link": reverse_lazy(
                            "admin:augmentations_augmentationparameter_changelist"
                        ),
                    },
                    {
                        "title": _("Dataset Augmentation"),
                        "icon": '',
                        "link": reverse_lazy(
                            "admin:augmentations_datasetaugmentation_changelist"
                        ),
                    },
                    {
                        "title": _("Dataset Augmentation Parameters"),
                        "icon": '',
                        "link": reverse_lazy(
                            "admin:augmentations_datasetaugmentationparameter_changelist"
                        ),
                    },
                ]
            },
            {
                "title": _("Models Management"),
                "collapsible": True,
                "items": [
                    {
                        "title": _("Model Tasks"),
                        "icon": "task",
                        "link": reverse_lazy(
                            "admin:ml_models_modeltask_changelist"
                            ),
                    },
                    {
                        "title": _("Model Framework"),
                        "icon": "flutter_dash",
                        "link": reverse_lazy(
                            "admin:ml_models_modelframework_changelist"
                            ),
                    },
                    {
                        "title": _("Model Tags"),
                        "icon": "sell",
                        "link": reverse_lazy(
                            "admin:ml_models_modeltag_changelist"
                            ),
                    },
                    {
                        "title": _("ML Models"),
                        "icon": "mindfulness",
                        "link": reverse_lazy(
                            "admin:ml_models_model_changelist"
                            ),
                    },
                    {
                        "title": _("Model Versions"),
                        "icon": "backup_table",
                        "link": reverse_lazy(
                            "admin:ml_models_modelversion_changelist"
                            ),
                    }
                ],
            },
            {
                "title": _("Training"),
                "collapsible": True,
                "items": [
                    {
                        "title": _("Training sessions"),
                        "icon": "model_training",
                        "link": reverse_lazy(
                            "admin:training_trainingsession_changelist"
                            ),
                    },  
                ]  
            },
            {
                "title": _("Inferences"),
                "collapsible": True,
                "items": [
                    {
                        "title": _("Prediction Results"),
                        "icon": "batch_prediction",
                        "link": reverse_lazy(
                            "admin:inferences_predictionimageresult_changelist"
                            ),
                    },
                    {
                        "title": _("Prediction Overlay"),
                        "icon": "shadow",
                        "link": reverse_lazy(
                            "admin:inferences_predictionoverlay_changelist"
                            ),
                    },   
                ]  
            }
 
        ],
    },
}
