# Generated by Django 4.2 on 2025-11-10 18:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0024_alter_version_storage_profile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('organizations', '0003_alter_organization_options_organization_created_by_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSessionActivity',
            fields=[
                ('session_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('last_activity', models.DateTimeField(auto_now=True)),
                ('actions_count', models.IntegerField(default=0)),
                ('annotations_created', models.IntegerField(default=0)),
                ('images_processed', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizations.organization')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_session_activity',
            },
        ),
        migrations.CreateModel(
            name='UserActivityMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_start', models.DateTimeField(db_index=True)),
                ('period_end', models.DateTimeField(db_index=True)),
                ('granularity', models.CharField(choices=[('hour', 'Hourly'), ('day', 'Daily'), ('week', 'Weekly'), ('month', 'Monthly')], default='day', max_length=10)),
                ('images_uploaded', models.IntegerField(default=0)),
                ('images_added_to_project', models.IntegerField(default=0)),
                ('total_upload_size_mb', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('annotations_created', models.IntegerField(default=0)),
                ('annotations_updated', models.IntegerField(default=0)),
                ('annotations_deleted', models.IntegerField(default=0)),
                ('manual_annotations', models.IntegerField(default=0)),
                ('ai_predictions_accepted', models.IntegerField(default=0)),
                ('ai_predictions_edited', models.IntegerField(default=0)),
                ('ai_predictions_rejected', models.IntegerField(default=0)),
                ('images_reviewed', models.IntegerField(default=0)),
                ('images_approved', models.IntegerField(default=0)),
                ('images_rejected', models.IntegerField(default=0)),
                ('images_finalized', models.IntegerField(default=0)),
                ('annotations_reviewed', models.IntegerField(default=0)),
                ('avg_annotation_time_seconds', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('avg_edit_magnitude', models.DecimalField(blank=True, decimal_places=4, help_text='Average change magnitude for edited predictions', max_digits=5, null=True)),
                ('jobs_completed', models.IntegerField(default=0)),
                ('last_activity', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizations.organization')),
                ('project', models.ForeignKey(blank=True, help_text='Null = organization-wide metrics', null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Activity Metrics',
                'verbose_name_plural': 'User Activity Metrics',
                'db_table': 'user_activity_metrics',
                'ordering': ['-period_start'],
            },
        ),
        migrations.CreateModel(
            name='ProjectActivityMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_start', models.DateTimeField(db_index=True)),
                ('period_end', models.DateTimeField(db_index=True)),
                ('granularity', models.CharField(default='day', max_length=10)),
                ('total_images', models.IntegerField(default=0)),
                ('images_unannotated', models.IntegerField(default=0)),
                ('images_annotated', models.IntegerField(default=0)),
                ('images_reviewed', models.IntegerField(default=0)),
                ('images_finalized', models.IntegerField(default=0)),
                ('total_annotations', models.IntegerField(default=0)),
                ('manual_annotations', models.IntegerField(default=0)),
                ('ai_predictions', models.IntegerField(default=0)),
                ('untouched_predictions', models.IntegerField(default=0, help_text='AI predictions not reviewed/edited')),
                ('edited_predictions', models.IntegerField(default=0)),
                ('rejected_predictions', models.IntegerField(default=0)),
                ('avg_annotations_per_image', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('annotations_per_hour', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('active_users', models.IntegerField(default=0, help_text='Users with activity in this period')),
                ('top_contributor_id', models.UUIDField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizations.organization')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.project')),
            ],
            options={
                'db_table': 'project_activity_metrics',
                'ordering': ['-period_start'],
            },
        ),
        migrations.CreateModel(
            name='ActivityEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='Unique identifier for the event', unique=True)),
                ('event_type', models.CharField(choices=[('image_upload', 'Image Uploaded'), ('image_add_project', 'Image Added to Project'), ('image_remove_project', 'Image Removed from Project'), ('annotation_create', 'Annotation Created'), ('annotation_update', 'Annotation Updated'), ('annotation_delete', 'Annotation Deleted'), ('annotation_review', 'Annotation Reviewed'), ('image_review', 'Image Reviewed'), ('image_finalize', 'Image Finalized'), ('job_assign', 'Job Assigned'), ('job_complete', 'Job Completed'), ('prediction_generate', 'Predictions Generated'), ('prediction_accept', 'Prediction Accepted'), ('prediction_edit', 'Prediction Edited'), ('prediction_reject', 'Prediction Rejected'), ('dataset_export', 'Dataset Exported'), ('dataset_version_create', 'Dataset Version Created')], db_index=True, max_length=50)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('metadata', models.JSONField(default=dict, help_text='\n        Flexible JSON field for event-specific data:\n        {\n            "image_id": "uuid",\n            "annotation_id": "uuid",\n            "annotation_count": 5,\n            "annotation_source": "manual",\n            "edit_magnitude": 0.2,\n            "confidence": 0.95,\n            "job_id": "uuid",\n            "status_from": "unannotated",\n            "status_to": "annotated",\n            "file_size_mb": 2.5,\n            "duration_seconds": 120\n        }\n        ')),
                ('duration_ms', models.IntegerField(blank=True, help_text='Action duration in milliseconds', null=True)),
                ('session_id', models.UUIDField(blank=True, db_index=True, help_text='Group related actions in same session', null=True)),
                ('source', models.CharField(default='web', help_text='Origin: web, api, mobile, automation', max_length=50)),
                ('organization', models.ForeignKey(help_text='Organization for tenant isolation', on_delete=django.db.models.deletion.CASCADE, to='organizations.organization')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.project')),
                ('user', models.ForeignKey(help_text='User who performed the action', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Activity Event',
                'verbose_name_plural': 'Activity Events',
                'db_table': 'activity_event',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AddIndex(
            model_name='usersessionactivity',
            index=models.Index(fields=['user', '-started_at'], name='user_sessio_user_id_577c34_idx'),
        ),
        migrations.AddIndex(
            model_name='usersessionactivity',
            index=models.Index(fields=['organization', 'is_active'], name='user_sessio_organiz_483f83_idx'),
        ),
        migrations.AddIndex(
            model_name='usersessionactivity',
            index=models.Index(fields=['-last_activity'], name='user_sessio_last_ac_45ac09_idx'),
        ),
        migrations.AddIndex(
            model_name='useractivitymetrics',
            index=models.Index(fields=['organization', 'granularity', '-period_start'], name='user_activi_organiz_d19847_idx'),
        ),
        migrations.AddIndex(
            model_name='useractivitymetrics',
            index=models.Index(fields=['organization', 'user', '-period_start'], name='user_activi_organiz_9811bb_idx'),
        ),
        migrations.AddIndex(
            model_name='useractivitymetrics',
            index=models.Index(fields=['project', '-annotations_created'], name='user_activi_project_053d88_idx'),
        ),
        migrations.AddIndex(
            model_name='useractivitymetrics',
            index=models.Index(fields=['project', '-images_reviewed'], name='user_activi_project_0df85d_idx'),
        ),
        migrations.AddIndex(
            model_name='useractivitymetrics',
            index=models.Index(fields=['user', 'organization', '-period_start'], name='user_activi_user_id_95f7a8_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='useractivitymetrics',
            unique_together={('user', 'organization', 'project', 'period_start', 'granularity')},
        ),
        migrations.AddIndex(
            model_name='projectactivitymetrics',
            index=models.Index(fields=['project', '-period_start'], name='project_act_project_629382_idx'),
        ),
        migrations.AddIndex(
            model_name='projectactivitymetrics',
            index=models.Index(fields=['organization', '-period_start'], name='project_act_organiz_c77a9d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='projectactivitymetrics',
            unique_together={('project', 'period_start', 'granularity')},
        ),
        migrations.AddIndex(
            model_name='activityevent',
            index=models.Index(fields=['organization', '-timestamp'], name='activity_ev_organiz_3a3a47_idx'),
        ),
        migrations.AddIndex(
            model_name='activityevent',
            index=models.Index(fields=['organization', 'event_type', '-timestamp'], name='activity_ev_organiz_1e1764_idx'),
        ),
        migrations.AddIndex(
            model_name='activityevent',
            index=models.Index(fields=['organization', 'user', '-timestamp'], name='activity_ev_organiz_b8d106_idx'),
        ),
        migrations.AddIndex(
            model_name='activityevent',
            index=models.Index(fields=['organization', 'project', '-timestamp'], name='activity_ev_organiz_710899_idx'),
        ),
        migrations.AddIndex(
            model_name='activityevent',
            index=models.Index(fields=['user', '-timestamp'], name='activity_ev_user_id_f3fd17_idx'),
        ),
        migrations.AddIndex(
            model_name='activityevent',
            index=models.Index(fields=['user', 'event_type', '-timestamp'], name='activity_ev_user_id_52fdf3_idx'),
        ),
        migrations.AddIndex(
            model_name='activityevent',
            index=models.Index(fields=['project', '-timestamp'], name='activity_ev_project_b23f46_idx'),
        ),
        migrations.AddIndex(
            model_name='activityevent',
            index=models.Index(fields=['session_id', 'timestamp'], name='activity_ev_session_7f1d62_idx'),
        ),
    ]
