# Generated by Django 4.2 on 2025-11-15 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0002_create_materialized_views'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrgActivitySummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('total_events', models.IntegerField()),
                ('active_users', models.IntegerField()),
                ('annotation_events', models.IntegerField()),
                ('image_events', models.IntegerField()),
                ('annotations_created', models.IntegerField()),
                ('images_reviewed', models.IntegerField()),
                ('images_uploaded', models.IntegerField()),
            ],
            options={
                'db_table': 'org_activity_summary',
                'ordering': ['-date'],
                'managed': False,
            },
        ),
    ]
