# Generated by Django 4.2 on 2025-05-23 07:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingsession',
            name='config',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trainingsession',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trainingsession',
            name='logs',
            field=models.TextField(blank=True, help_text='Short log summary or status messages', null=True),
        ),
        migrations.AlterField(
            model_name='trainingsession',
            name='log_path',
            field=models.CharField(blank=True, help_text='Path to the full training log file', max_length=1024, null=True),
        ),
    ]
