# Generated by Django 4.2 on 2025-05-24 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0002_trainingsession_config_trainingsession_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingsession',
            name='metrics',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trainingsession',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
