# Generated by Django 4.2 on 2025-11-30 18:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("storage", "0001_initial"),
        ("ml_models", "0006_alter_modelversion_options_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("training", "0003_trainingsession_metrics_trainingsession_updated_at"),
    ]

    operations = [
        migrations.CreateModel(
            name="TrainingCheckpoint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "epoch",
                    models.PositiveIntegerField(
                        help_text="Epoch number when checkpoint was saved"
                    ),
                ),
                (
                    "checkpoint_key",
                    models.CharField(
                        help_text="Storage key for checkpoint file", max_length=500
                    ),
                ),
                (
                    "metrics",
                    models.JSONField(
                        blank=True, default=dict, help_text="Metrics at this checkpoint"
                    ),
                ),
                (
                    "is_best",
                    models.BooleanField(
                        default=False, help_text="Whether this was the best checkpoint"
                    ),
                ),
                (
                    "file_size_bytes",
                    models.BigIntegerField(
                        blank=True, help_text="Size of checkpoint file", null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name_plural": "Training Checkpoints",
                "db_table": "training_checkpoint",
                "ordering": ["epoch"],
            },
        ),
        migrations.AlterModelOptions(
            name="trainingsession",
            options={
                "ordering": ["-created_at"],
                "verbose_name_plural": "Training Sessions",
            },
        ),
        migrations.RemoveField(
            model_name="trainingsession",
            name="log_path",
        ),
        migrations.RemoveField(
            model_name="trainingsession",
            name="logs",
        ),
        migrations.RemoveField(
            model_name="trainingsession",
            name="metrics",
        ),
        migrations.AddField(
            model_name="trainingsession",
            name="best_metrics",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Best metrics achieved during training",
            ),
        ),
        migrations.AddField(
            model_name="trainingsession",
            name="compute_resource",
            field=models.CharField(
                blank=True,
                help_text="Compute resource used (GPU type, worker name, etc.)",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="trainingsession",
            name="current_epoch",
            field=models.PositiveIntegerField(
                default=0, help_text="Current training epoch"
            ),
        ),
        migrations.AddField(
            model_name="trainingsession",
            name="current_metrics",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Current/latest metrics from training",
            ),
        ),
        migrations.AddField(
            model_name="trainingsession",
            name="error_traceback",
            field=models.TextField(
                blank=True, help_text="Full error traceback for debugging"
            ),
        ),
        migrations.AddField(
            model_name="trainingsession",
            name="estimated_time_remaining",
            field=models.DurationField(
                blank=True, help_text="Estimated time until completion", null=True
            ),
        ),
        migrations.AddField(
            model_name="trainingsession",
            name="log_file_key",
            field=models.CharField(
                blank=True,
                help_text="Storage key for detailed log file",
                max_length=500,
            ),
        ),
        migrations.AddField(
            model_name="trainingsession",
            name="log_summary",
            field=models.TextField(
                blank=True, help_text="Short summary of training progress/status"
            ),
        ),
        migrations.AddField(
            model_name="trainingsession",
            name="session_id",
            field=models.CharField(
                default=django.utils.timezone.now,
                help_text="Unique identifier for this training session",
                max_length=255,
                unique=True,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="trainingsession",
            name="storage_profile",
            field=models.ForeignKey(
                default=1,
                help_text="Storage profile for logs and checkpoints",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="training_sessions",
                to="storage.storageprofile",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="trainingsession",
            name="task_id",
            field=models.CharField(
                blank=True,
                help_text="Celery task ID for this training run",
                max_length=255,
                null=True,
                unique=True,
            ),
        ),
        migrations.AddField(
            model_name="trainingsession",
            name="total_epochs",
            field=models.PositiveIntegerField(
                default=0, help_text="Total number of epochs to train"
            ),
        ),
        migrations.AddField(
            model_name="trainingsession",
            name="triggered_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="triggered_training_sessions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="trainingsession",
            name="completed_at",
            field=models.DateTimeField(
                blank=True,
                help_text="When training finished (success or failure)",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="trainingsession",
            name="config",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Training configuration for this specific run",
            ),
        ),
        migrations.AlterField(
            model_name="trainingsession",
            name="error_message",
            field=models.TextField(
                blank=True, help_text="Error message if training failed"
            ),
        ),
        migrations.AlterField(
            model_name="trainingsession",
            name="model_version",
            field=models.ForeignKey(
                help_text="Model version being trained",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="training_sessions",
                to="ml_models.modelversion",
            ),
        ),
        migrations.AlterField(
            model_name="trainingsession",
            name="progress",
            field=models.FloatField(
                default=0.0, help_text="Training progress percentage (0-100)"
            ),
        ),
        migrations.AlterField(
            model_name="trainingsession",
            name="started_at",
            field=models.DateTimeField(
                blank=True, help_text="When training actually started", null=True
            ),
        ),
        migrations.AlterField(
            model_name="trainingsession",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("queued", "Queued"),
                    ("initializing", "Initializing"),
                    ("running", "Running"),
                    ("completed", "Completed"),
                    ("failed", "Failed"),
                    ("cancelled", "Cancelled"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AddIndex(
            model_name="trainingsession",
            index=models.Index(
                fields=["model_version", "created_at"],
                name="training_se_model_v_97031c_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="trainingsession",
            index=models.Index(
                fields=["status", "created_at"], name="training_se_status_4d7543_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="trainingsession",
            index=models.Index(
                fields=["task_id"], name="training_se_task_id_2f5550_idx"
            ),
        ),
        migrations.AddField(
            model_name="trainingcheckpoint",
            name="training_session",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="checkpoints",
                to="training.trainingsession",
            ),
        ),
        migrations.AddIndex(
            model_name="trainingcheckpoint",
            index=models.Index(
                fields=["training_session", "epoch"],
                name="training_ch_trainin_59df1c_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="trainingcheckpoint",
            index=models.Index(
                fields=["is_best"], name="training_ch_is_best_24e231_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="trainingcheckpoint",
            unique_together={("training_session", "epoch")},
        ),
    ]
