# Generated by Django 4.2 on 2026-04-25 07:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('ml_models', '0008_modelversion_tags'),
        ('compute', '0003_inferencejob_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('training', '0004_trainingcheckpoint_alter_trainingsession_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RetrainingPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('policy_id', models.CharField(default=uuid.uuid4, editable=False, help_text='Unique identifier for this retraining policy', max_length=255, unique=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('trigger_type', models.CharField(choices=[('annotation_count', 'New Annotation Count'), ('correction_rate', 'Prediction Correction Rate'), ('time_elapsed', 'Time Since Last Training'), ('combined', 'Combined Conditions')], default='annotation_count', max_length=30)),
                ('min_new_annotations', models.PositiveIntegerField(default=100, help_text='Retrain when this many new reviewed annotations accumulate')),
                ('min_correction_rate', models.FloatField(blank=True, help_text='Retrain when FP+FN rate exceeds this fraction (0–1)', null=True)),
                ('max_days_since_training', models.PositiveIntegerField(blank=True, help_text='Retrain if the latest trained version is older than N days', null=True)),
                ('lookback_days', models.PositiveIntegerField(default=30, help_text='Count new annotations within this rolling window (days)')),
                ('auto_create_dataset_version', models.BooleanField(default=True, help_text='Automatically snapshot current annotations into a new dataset version')),
                ('auto_submit_training', models.BooleanField(default=True, help_text='Automatically submit a new training job after creating the dataset version')),
                ('min_hours_between_runs', models.PositiveIntegerField(default=24, help_text='Minimum hours between two automatic retraining runs')),
                ('last_triggered_at', models.DateTimeField(blank=True, help_text='Timestamp of the last automatic retraining trigger', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('compute_profile', models.ForeignKey(blank=True, help_text='Compute profile to use for the triggered training run', null=True, on_delete=django.db.models.deletion.SET_NULL, to='compute.computeprofile')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='retraining_policies', to='ml_models.model')),
            ],
            options={
                'verbose_name_plural': 'Retraining Policies',
                'db_table': 'retraining_policy',
            },
        ),
        migrations.AddIndex(
            model_name='retrainingpolicy',
            index=models.Index(fields=['model', 'is_active'], name='retraining__model_i_1fc725_idx'),
        ),
    ]
