# Generated by Django 4.2 on 2025-10-26 15:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('memberships', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectmembership',
            name='created_at',
        ),
        migrations.AddField(
            model_name='projectmembership',
            name='joined_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
