# Generated by Django 4.2 on 2025-10-27 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memberships', '0002_remove_projectmembership_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationmembership',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('pending', 'Pending'), ('suspended', 'Suspended')], db_index=True, default='active', help_text='Membership status in this organization', max_length=20),
        ),
        migrations.AddIndex(
            model_name='organizationmembership',
            index=models.Index(fields=['user', 'organization'], name='organizatio_user_id_3409fd_idx'),
        ),
        migrations.AddIndex(
            model_name='organizationmembership',
            index=models.Index(fields=['organization', 'role'], name='organizatio_organiz_5e8766_idx'),
        ),
        migrations.AddIndex(
            model_name='organizationmembership',
            index=models.Index(fields=['organization', 'status'], name='organizatio_organiz_f79e6d_idx'),
        ),
    ]
