# Generated by Django 4.2 on 2026-04-09 16:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
        ('memberships', '0004_organizationmembership_invited_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationmembership',
            name='billing_enabled',
            field=models.BooleanField(db_index=True, default=False, help_text='Whether to track billable actions for this user in this org'),
        ),
        migrations.AddField(
            model_name='organizationmembership',
            name='billing_rate_card',
            field=models.ForeignKey(blank=True, help_text='Personal rate card for this user in this organization', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_org_members', to='billing.billingratecard'),
        ),
        migrations.AddField(
            model_name='organizationmembership',
            name='contract_end_date',
            field=models.DateField(blank=True, help_text='When contract ends (null = ongoing)', null=True),
        ),
        migrations.AddField(
            model_name='organizationmembership',
            name='contract_start_date',
            field=models.DateField(blank=True, help_text='When contract started', null=True),
        ),
        migrations.AddField(
            model_name='organizationmembership',
            name='contractor_company',
            field=models.CharField(blank=True, help_text='External company/agency this contractor works for', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='organizationmembership',
            name='hourly_rate',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Optional hourly rate for time-based billing', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='organizationmembership',
            name='is_external_annotator',
            field=models.BooleanField(db_index=True, default=False, help_text='Whether this user is an external contractor in this organization'),
        ),
        migrations.AddField(
            model_name='projectmembership',
            name='billing_enabled',
            field=models.BooleanField(db_index=True, default=False, help_text='Whether to track billable actions for this user in this project'),
        ),
        migrations.AddField(
            model_name='projectmembership',
            name='billing_rate_card',
            field=models.ForeignKey(blank=True, help_text='Project-specific rate card for this user', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_project_members', to='billing.billingratecard'),
        ),
        migrations.AddField(
            model_name='projectmembership',
            name='hourly_rate',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Project-specific hourly rate', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='projectmembership',
            name='is_external_annotator',
            field=models.BooleanField(db_index=True, default=False, help_text='Whether this user is external contractor for this specific project'),
        ),
        migrations.AddIndex(
            model_name='organizationmembership',
            index=models.Index(fields=['organization', 'is_external_annotator'], name='organizatio_organiz_5ebbe2_idx'),
        ),
        migrations.AddIndex(
            model_name='organizationmembership',
            index=models.Index(fields=['organization', 'billing_enabled'], name='organizatio_organiz_fb10ba_idx'),
        ),
        migrations.AddIndex(
            model_name='projectmembership',
            index=models.Index(fields=['project', 'is_external_annotator'], name='project_mem_project_4ff466_idx'),
        ),
        migrations.AddIndex(
            model_name='projectmembership',
            index=models.Index(fields=['project', 'billing_enabled'], name='project_mem_project_ae2896_idx'),
        ),
    ]
