# Generated by Django 4.2 on 2025-04-12 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organization',
            name='description',
        ),
        migrations.AddField(
            model_name='organization',
            name='slug',
            field=models.SlugField(null=True, unique=True),
        ),
    ]
