# Generated by Django 4.2 on 2025-10-22 19:05

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('organizations', '0002_remove_organization_description_organization_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='organization',
            options={'ordering': ['-created_at'], 'verbose_name': 'Organization', 'verbose_name_plural': 'Organizations'},
        ),
        migrations.AddField(
            model_name='organization',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='organizations_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='organization',
            name='current_storage_gb',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Current storage usage in GB', max_digits=10),
        ),
        migrations.AddField(
            model_name='organization',
            name='description',
            field=models.TextField(blank=True, help_text='Organization description', null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='display_name',
            field=models.CharField(blank=True, help_text='Public-facing display name (defaults to name)', max_length=255),
        ),
        migrations.AddField(
            model_name='organization',
            name='email',
            field=models.EmailField(blank=True, help_text='Organization contact email', max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, help_text='Whether the organization is active'),
        ),
        migrations.AddField(
            model_name='organization',
            name='logo_url',
            field=models.URLField(blank=True, help_text='Organization logo URL', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='max_models',
            field=models.IntegerField(default=10, help_text='Maximum number of trained models'),
        ),
        migrations.AddField(
            model_name='organization',
            name='max_projects',
            field=models.IntegerField(default=5, help_text='Maximum number of projects allowed'),
        ),
        migrations.AddField(
            model_name='organization',
            name='max_storage_gb',
            field=models.IntegerField(default=10, help_text='Maximum storage in GB'),
        ),
        migrations.AddField(
            model_name='organization',
            name='max_users',
            field=models.IntegerField(default=5, help_text='Maximum number of users'),
        ),
        migrations.AddField(
            model_name='organization',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, help_text='Additional metadata'),
        ),
        migrations.AddField(
            model_name='organization',
            name='org_id',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='Unique UUID identifier for the organization', unique=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='owner',
            field=models.ForeignKey(default=1, help_text='Organization owner', on_delete=django.db.models.deletion.PROTECT, related_name='owned_organizations', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='organization',
            name='settings',
            field=models.JSONField(blank=True, default=dict, help_text='Organization-specific settings and configurations'),
        ),
        migrations.AddField(
            model_name='organization',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('suspended', 'Suspended'), ('trial', 'Trial'), ('inactive', 'Inactive')], db_index=True, default='active', help_text='Organization account status', max_length=20),
        ),
        migrations.AddField(
            model_name='organization',
            name='subscription_end_date',
            field=models.DateTimeField(blank=True, help_text='When the current subscription ends', null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='subscription_plan',
            field=models.CharField(choices=[('free', 'Free'), ('starter', 'Starter'), ('professional', 'Professional'), ('enterprise', 'Enterprise')], db_index=True, default='free', help_text='Current subscription plan', max_length=20),
        ),
        migrations.AddField(
            model_name='organization',
            name='subscription_start_date',
            field=models.DateTimeField(blank=True, help_text='When the current subscription started', null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='trial_end_date',
            field=models.DateTimeField(blank=True, help_text='Trial period end date', null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='organizations_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='organization',
            name='website',
            field=models.URLField(blank=True, help_text='Organization website', null=True),
        ),
        migrations.AlterField(
            model_name='organization',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='organization',
            name='name',
            field=models.CharField(help_text='Organization name', max_length=255, unique=True, validators=[django.core.validators.MinLengthValidator(2)]),
        ),
        migrations.AlterField(
            model_name='organization',
            name='slug',
            field=models.SlugField(default='perceptra-hub', help_text='URL-friendly identifier', max_length=255, unique=True, validators=[django.core.validators.RegexValidator(message='Slug must contain only lowercase letters, numbers, and hyphens', regex='^[a-z0-9-]+$')]),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name='organization',
            index=models.Index(fields=['slug', 'is_active'], name='organizatio_slug_312faa_idx'),
        ),
        migrations.AddIndex(
            model_name='organization',
            index=models.Index(fields=['status', 'is_active'], name='organizatio_status_a716ff_idx'),
        ),
        migrations.AddIndex(
            model_name='organization',
            index=models.Index(fields=['subscription_plan', 'status'], name='organizatio_subscri_3fff09_idx'),
        ),
        migrations.AddIndex(
            model_name='organization',
            index=models.Index(fields=['owner', 'is_active'], name='organizatio_owner_i_75ae52_idx'),
        ),
    ]
