# Generated by Django 4.2 on 2025-11-19 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0003_alter_organization_options_organization_created_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='is_vendor',
            field=models.BooleanField(db_index=True, default=False, help_text='Whether this is an annotation vendor organization'),
        ),
    ]
